<?php
View::content();

?>

<?php echo Form::open("entidad/acceso/" . $usuario->Id, 'POST', 'id="frmacceso"'); ?>
<div class="col-sm-12">                  
    <div class="panel panel-success">
        <div class="panel-heading">CAMBIO DE CONTRASEÑA (Solo casos especiales)</div>
        <div class="panel-body">




            <div  id="nombrefisica" style="display: block;">

                <div class="col-sm-12">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Razón Social / Operacion:    
                            </div>
                            <?php echo Form::text('nombrecompleto', 'class="form-control" disabled ',@$usuario->nombrecompleto); ?>
                        </div>
                    </div>
                </div> 

                <br/>
                <br/>
                <br/>

            </div> 
 
            <div class="panel panel-success" >
                <div class="panel-heading" >DATOS  DE ACCESO </div>
                <div class="panel-body">

                    <div class="col-sm-4">
                        <label for="lastName">Usuario<small class="required">*</small></label>
                        <div class="input-group">
                            <?php echo Form::text('usuario.Usr', 'class="form-control" required disabled'); ?>                                    </div>
                    </div>
                   
                    <div class="col-sm-4">
                        <label for="lastName">Contraseña<small class="required">*</small></label>
                        <div class="input-group">
                              <?php echo Form::pass('usuario.Pass', 'class="form-control"  required  maxlength="16" title="Puede utilizar letras (Mayusculas,Minusculas), Numeros o los simbolos siguientes !+*- :" '); ?>                        </div>         
                    </div>
                    <div class="col-sm-4">
                        <label for="lastName">Repetir Contraseña<small class="required">*</small></label>
                        <div class="input-group">  
                        <?php echo Form::pass('usuario.Pas', 'class="form-control" required'); ?>
                        </div>
                    </div>
                    <div class="col-sm-10">
                        <div class="input-group"> .
                        </div>
                    </div>
                    <div class="col-sm-12">
                  <div class="alert alert-warning alert-dismissible" role="alert">
                      
                
  La contraseña debe tener al entre 8 y 16 caracteres.<br/>
  Al menos un dígito.<br/> Al menos una minúscula. <br/>  Al menos una mayúscula. <br/>Puede tener otros símbolos.
</div>  
                </div>
                </div>
            </div>

            
        </div> 
    </div>
</div>

<table width="100%"  border="0">


    <tr>

    <tr>
        <?php $url = PUBLIC_PATH; ?>
        <td width="50%" style="text-align: center;  "><?php echo Form::button('Regresar', 'id="btnSig" class="btn btn-danger"  onclick="regresar()" '); ?> </td>
        <td width="50%" style="text-align: center;  "><?php echo Form::button('Guardar', ' class="btn btn-danger"  onclick="guardar()" '); ?> </td>


    </tr>
</tr>  
</table>
<?php echo Form::hidden('usuario.Id', 'class="form-control"  '); ?>
<?php echo Form::hidden('usuario.entidad_id', 'class="form-control"  '); ?>
<?php echo Form::close(); ?>

<script>
    function guardar() {
        
        var cadena=/^(?=\w*\d)(?=\w*[A-Z])(?=\w*[a-z])\S{8,16}$/;
        
        Pass = $("#usuario_Pass").val();
        Pas = $("#usuario_Pas").val();
        
        
         if (Pass == "" ){
                alert("La Nueva Contraseña es Necesaria");
            }
        else if (Pass != Pas){
                alert("La contraseña no coincide ");
            }
       else if (Pass.match(cadena)) {
          $("#frmacceso").submit();
        }else{
          alert("La contraseña con cumple con la validacion requerida ");    
        } 
        
        
    }
    function regresar() {
        window.location.href = "<?php echo $url . "entidad/listado"; ?>";
    }
    
  
</script>

