<?php
View::content();

?>
<div id="form_container" style="width:100%">
    <h1><a></a></h1>
    <br>
</div>
<?php echo Form::open("usuario/editar/", 'POST', 'id="frmacceso"'); ?>
<div class="col-sm-12">                  
    <div class="panel panel-success">
        <div class="panel-heading">ACTUALIZAR DATOS</div>
        <div class="panel-body">




            <div  id="nombrefisica" style="display: block;">

                <div class="col-sm-8">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon"> Empleado:    
                            </div>
                            <?php echo Form::text("empleado.nombre_completo", " class='form-control ' disabled  ");?>
                        </div>
                    </div>
                </div> 

                <br/>
                <br/>
                <br/>

            </div> 
 
            <div class="panel panel-success" >
                <div class="panel-heading" >DATOS  DE ACCESO </div>
                <div class="panel-body">
                    
                    <div class="col-sm-4">
                        <label for="lastName">Tipo<small class="required">*</small></label>
                        <div class="input-group">
                           <?php
                        $tipo_valor = array(""=>"Seleccione","1"=>"ADMINISTRADOR","2"=>"VENTAS","3"=>"ALMACEN");
                        
                        echo Form::Select("usuario.Tipo", $tipo_valor, "class='form-control' ",$usuario->Tipo );
                        ?>                                       </div>
                    </div>
                    <div class="col-sm-5">
                        <label for="lastName">Usuario<small class="required">*</small></label>
                        <div class="input-group">
                            <?php echo Form::text('usuario.Usr', 'class="form-control" required readonly'); ?>                                    </div>
                    </div>
                   <div class="col-sm-12">
                        <br/>
                    </div>
                    <div class="col-sm-4">
                        <label for="lastName">Contraseña<small class="required">*</small></label>
                        <div class="input-group">
                              <?php echo Form::pass('usuario.Pass', 'class="form-control"  required  maxlength="16" title="Puede utilizar letras (Mayusculas,Minusculas), Numeros o los simbolos siguientes !+*- :" ',""); ?>                        </div>         
                    </div>
                    <div class="col-sm-4">
                        <label for="lastName">Repetir Contraseña<small class="required">*</small></label>
                        <div class="input-group">  
                        <?php echo Form::pass('usuario.Pas', 'class="form-control" required',""); ?>
                        </div>
                    </div>
                    <div class="col-sm-10">
                        <div class="input-group"> .
                        </div>
                    </div>
                    <div class="col-sm-12">
                  <div class="alert alert-warning alert-dismissible" role="alert">
                      
                
  La contraseña debe tener al entre 8 y 16 caracteres.<br/>
  Al menos un dígito.<br/> Al menos una minúscula. <br/>  Al menos una mayúscula. <br/>Puede tener otros símbolos.
</div>  
                </div>
                </div>
            </div>

            
        </div> 
    </div>
</div>

<table width="100%"  border="0">


    <tr>

    <tr>
        <?php $url = PUBLIC_PATH; ?>
        <td width="50%" style="text-align: center;  "><?php echo Form::button('Regresar', 'id="btnSig" class="btn btn-danger"  onclick="regresar()" '); ?> </td>
        <td width="50%" style="text-align: center;  "><?php echo Form::button('Guardar', ' class="btn btn-success"  onclick="guardar()" '); ?> </td>


    </tr>
</tr>  
</table>
<?php echo Form::hidden('usuario.Id', 'class="form-control"  '); ?>
<?php echo Form::close(); ?>

<script>
    function guardar() {
        
        var cadena=/^(?=\w*\d)(?=\w*[A-Z])(?=\w*[a-z])\S{8,16}$/;
        
        Pass = $("#usuario_Pass").val();
        Pas = $("#usuario_Pas").val();
        
        
         if (Pass == "" ){
                alert("La Nueva Contraseña es Necesaria");
            }
        else if (Pass != Pas){
                alert("La contraseña no coincide ");
            }
       else if (Pass.match(cadena)) {
          $("#frmacceso").submit();
        }else{
          alert("La contraseña con cumple con la validacion requerida ");    
        } 
        
        
    }
    function regresar() {
        window.location.href = "<?php echo $url . "usuario/"; ?>";
    }
    
  
</script>

