<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div id="form_container" style="width:100%">
    <br>
    <h1><a></a></h1>
<?php View::partial("formatoTabla",false,array('Encabezado'=>$encabezado,'Model'=>$result,'Campos'=>$campos,'ctrlActualizar'=>"actualizar/",'ctrlcrear'=>"crear/",'ctrleditar'=>"editar/"));  ?>
</div>

