<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<?php View::content(); ?>
<body id="cuerpo_principal">

<div id="form_container" style="width:100%;" >

    <h1><a></a></h1>
    <div id="titulo_superior"> 
        <div id="texto_superior"  >
                 <?php echo "Almacenes" ?> 
            </div>
            <div style="text-align:right;margin: 0 0; width:49%; float: left; ">
                <div class='btn'>
                    
                </div>
            </div>
    </div>
    <?php echo Form::open("reportes/" . $accion,"POST","id='frmalmacen'"); ?>


   
    
    <div id="margen" >
<fieldset>     
<table width="50%" border="0" class="letra">
  <tr>
    <td >Producto</td>
    <td width="29%"><?php echo Form::dbSelect("almacen.almacen_id","descripcion",array("almacen","listar"),'Seleccione..','type="text"  class="form-control" style="width:425px"');?></td>
  </tr>
 
  
  
  <tr>
      <td width="13%" >
      &nbsp;Tipo</td>
    <td width="13%" > 
    <?php    
         $arregloEstado = array(''=>'Seleccione...','RESUMEN'=>'Resumen','DETALLE'=>'Detalle');?>
                <?php echo Form::Select('almacen.tipo', $arregloEstado,'type="text" required class="form-control"'); ?>
    </select></td>
   
  </tr>
  <tr>
      <td width="13%" >
      &nbsp;Ciclo</td>
    <td width="13%" > 
    <?php echo Form::dbSelect("ciclo", 'ciclo', array('ciclocosecha', 'listar', 0), '- Seleccione -'," class='form-control ' ");?>
    </select></td>
   
  </tr>
</table>
</fieldset>


        </br>
            <?php $url = "'" . PUBLIC_PATH . "reportes"; ?>
        <table width="100%">
        <tr align="center">
            <td width="25%">     
            <?php echo Form::button("Cancelar", 'class="CSSButton" onclick="window.location = ' . $url . '" '); ?>
            </td>
            <td>
            <?php echo Form::reset('Reiniciar', 'class="CSSButton"'); //Crea un botón con el texto 'reiniciar';?>
            </td>
            <td width="25%">
            <?php echo Form::submit('Generar', 'type="submit" onclick="reporte(1)" class="CSSButton"'); ?>       
            </td>
            <td width="25%">
            <?php echo Form::submit('Excel', 'id="Excel" onclick="reporte(2)" name="Excel" class="CSSButton"'); ?>       
            </td>
        </tr>
     </table>
     
  </div> 
</div>
    </br>
<?php echo form::hidden('tipoReporte');?>
<?php echo Form::close(); ?>
<?php echo Html::img('bottom.png','',"id='bottom' style='width:90%'");?>
</body>

<script type="text/javascript">
  function reporte(vr){
    if(vr==2) vr='excel'
     $('#tipoReporte').val(vr); 
                       
                    
}  
  </script>  