<?php
load::lib('tcpdf');

$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false); 
ob_end_clean();
// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('');
$pdf->SetTitle('Reportes');
$pdf->SetSubject('');
//================================================================
//VARIABLES POR DECLARAR
$numEvento="PENDIENTE";
//================================================================
//================ SE GENERAN DATOS DE LA POLIZA  ==================
$logo='img/logo.jpg';
$titulo='INSTITUTO ESTATAL DE EDUCACION PARA ADULTOS';
$subtitulo1=$tituloReporte;
$subtitulo2='ALMACEN ESTATAL';
$url='';

// set default header data
/*if ($miles==1){
    $pdf->SetHeaderData($logo, 11, $titulo , $subtitulo1."\n".$subtitulo2."\n  (en miles de pesos)" ,"\n".$url,'',array(190,190,190));
}else{*/
    $pdf->SetHeaderData($logo, 11, $titulo , $subtitulo1."\n".$subtitulo2,$url,'',array(190,190,190));
//}
    

// set default footer data
$pdf->SetFooterData('',array(190,190,190),"");

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN,'' , 8));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

//set margins
$pdf->SetMargins(10,20,10);//PDF_MARGIN_LEFT, '20', PDF_MARGIN_RIGHT
$pdf->SetHeaderMargin('5');//PDF_MARGIN_HEADER
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);



//set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

//set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

$pdf->setPageOrientation('P'); // PDF_PAGE_ORIENTATION---> 'L' or 'P'
// ---------------------------------------------------------

// set default font subsetting mode
$pdf->setFontSubsetting(true);

// set default font subsetting mode
$pdf->setFontSubsetting(true);
// Set font
// dejavusans is a UTF-8 Unicode font, if you only need to
// print standard ASCII chars, you can use core fonts like
// helvetica or times to reduce file size.
//$pdf->SetFont('dejavusans', , 8, , true);

// Add a page
// This method has several options, check the source code documentation for more information.
$pdf->AddPage();


// Set some content to print
$html ='<style>
	.negrita{
            font-size: 10px; 
            color: #333;
            font-weight:bold;
	}
        .nonegrita{
            font-size: 10px; 
            color: #333;
            text-align: center; vertical-align: bottom;
        }
        .nonegrita1{
            font-size: 7px; 
            color: #333;
            text-align: center; vertical-align: bottom;
        }
        .divcentrar{
            font-size: 10px; 
            color: #333;
           
        }
        .mitabla{
		font-size: 10px; 
		color: #333; 
	}
        </style>



    
<table align="left" width="100%" border="0">
    
    <thead>
     <tr style="font-size:10px;text-align:left;font-style:italic">
        <td width="20%" align="left" >Desde el dia:  '.strftime("%d-%m-%Y", strtotime($fechaInicial)).'</td>
        <td width="20%" align="center" ></td>
        <td width="20%" align="center" ></td>
        <td width="20%" align="center" ></td>
        <td width="20%" align="center" >Hasta el dia:  '.strftime("%d-%m-%Y", strtotime($fechaFinal)).'</td>
        
      </tr> 
      </thead>
      </table>
      <table align="left" width="100%" border="0">
   <tr class="negrita">
        <td width="10%" align="center"> </td>
        <td  align="center" width="55%"> </td>
        <td  align="center" width="20%"> </td>
        <td  align="center" width="15%"> </td>
    </tr>
    </table>
      <table align="left" width="100%" border="0">
    
    <thead>
  
      <tr style="font-size:10px;text-align:left;font-style:italic">
        <td width="10%" align="left" style="border-bottom:1px dashed #000000;">#</td>
        <td width="20%" align="center" style="border-bottom:1px dashed #000000;">Clave</td>
        <td width="40%" align="center" style="border-bottom:1px dashed #000000;">Descripcion</td>
        <td width="20%" align="center" style="border-bottom:1px dashed #000000;">Unidad Salida</td>
        <td width="10%" align="center" style="border-bottom:1px dashed #000000;">Cantidad</td>      
      </tr>
      </thead>
      
     
     
      
    
    ';
$clasificacionId="0";

$total=0;
$html.= '
        
            <tr class="negrita">
                    <td width="10%"><div class="divcentrar"></div></td>
                    <td width="50%" align="left"></td>
                    <td width="40%"><div class="divcentrar"></div></td>
                    
            </tr>
            ';
$i=1;
 if ($departamento=="0"){
   $condicion=" and  (ent.FECHA_ENTREGA >= '$fechaInicial' and ent.FECHA_ENTREGA <= '$fechaFinal' ) "; 
   if($producto!="0"){ $condicion=$condicion. " and detEn.PRODUCTO_ID=$producto";}
   $detalle1=Load::model('entrega')->listarDepartamento($condicion);
   foreach ($detalle1 as $datoDetalle){
       $condicion1="";
   $html.= '
        
            <tr class="negrita">
        <td width="99%" align="left" colspan="2"> >>>>  '.$datoDetalle->DESCRIPCION.'</td>        
                    
            </tr>
            ';
   
    if($producto!="0"){
             $condicion1=$condicion." and (detEn.PRODUCTO_ID=$producto) and ent.DEPARTAMENTO_ID=$datoDetalle->DEPARTAMENTO_ID";
    }else{
            $condicion1=$condicion."  and ent.DEPARTAMENTO_ID=$datoDetalle->DEPARTAMENTO_ID";
    }
    
   $movimientos=Load::model('entrega')->buscaProducto($condicion1);
   foreach ($movimientos as $dato){
    $condicionTotal=" and  (ent.FECHA_ENTREGA >= '$fechaInicial' and ent.FECHA_ENTREGA <= '$fechaFinal' ) and detEn.PRODUCTO_ID=$dato->ID and ent.DEPARTAMENTO_ID=$datoDetalle->DEPARTAMENTO_ID and ent.ESTADO='Activo'";
    $detalle=Load::model('detalle_entrega')->sumaCantidad($condicionTotal);
    if(($detalle->CANTIDAD=="") || ($detalle->CANTIDAD == NULL)){$cantidad=0;}else{$cantidad=$detalle->CANTIDAD;}
    $presentacion=Load::model('presentacion')->listarXid($dato->UNIDAD_SALIDA);
    $descripcion=$presentacion->DESCRIPCION;
    $html.= '
        
            <tr class="nonegrita">
        <td width="10%" align="left" >'.$i.'</td>
        <td width="20%" align="left" >'.$dato->CLAVE_ARTICULO.'</td>
        <td width="40%" align="left" >'.$dato->DESCRIPCION.'</td>
        <td width="20%" align="left" >'.$descripcion.'</td>
        <td width="10%" align="right" >'.number_format($cantidad,0,'.',',').'</td>
                    
            </tr>
            ';
    $i++;
    $total=$total+$cantidad;
      
}
   
   }
 
 }  else {
       
foreach ($movimientos as $dato){
    
    $condicionTotal=" and  (ent.FECHA_ENTREGA >= '$fechaInicial' and ent.FECHA_ENTREGA <= '$fechaFinal' ) and detEn.PRODUCTO_ID=$dato->ID and ent.DEPARTAMENTO_ID=$departamento and ent.ESTADO='Activo'";
    
    
    $detalle=Load::model('detalle_entrega')->sumaCantidad($condicionTotal);
    if(($detalle->CANTIDAD=="") || ($detalle->CANTIDAD == NULL)){$cantidad=0;}else{$cantidad=$detalle->CANTIDAD;}
    $presentacion=Load::model('presentacion')->listarXid($dato->UNIDAD_SALIDA);
    $descripcion=$presentacion->DESCRIPCION;
    $html.= '
        
            <tr class="nonegrita">
        <td width="10%" align="left" >'.$i.'</td>
        <td width="20%" align="left" >'.$dato->CLAVE_ARTICULO.'</td>
        <td width="40%" align="left" >'.$dato->DESCRIPCION.'</td>
        <td width="20%" align="left" >'.$descripcion.'</td>
        <td width="10%" align="right" >'.number_format($cantidad,0,'.',',').'</td>
                    
            </tr>
            ';
    $i++;
    $total=$total+$cantidad;
      /*  $detalle=Load::model('detalle_entrega')->sumaCantidad($dato->PRODUCTO_ID);
       $subtotal=0;
        foreach ($detalle as $detalleLote){
           
             $concepto=Load::model('conceptoMovimiento')->listarXid($detalleLote->TIPO_MOVIMIENTO);
             if($concepto->TIPO_MOVIMIENTO=="S"){
             $detalleLote->CANTIDAD=$detalleLote->CANTIDAD * (-1);
             } 
             $subtotal+=$detalleLote->CANTIDAD;
        $html.= '
            <tr class="nonegrita1">
                    <td width="10%" align="right">'.strftime("%d-%m-%Y", strtotime($detalleLote->FECHA_DOCUMENTO)).'</td>
                    <td width="30%" align="right">'.$detalleLote->REFERENCIA.'</td>
                    <td width="20%"><div class="divcentrar">'.$concepto->TIPO_MOVIMIENTO.'</div></td>
                    <td  align="center" width="20%" align="right" >'.$concepto->DESCRIPCION.' </td>
                    <td  width="10%" align="right">'.$detalleLote->CANTIDAD.'</td>
                    <td  width="10%" align="right">'.$detalleLote->EXISTENCIA.'</td>    
            </tr>
            ';
        } */
        
      
    
    
}
 }
 $html.= '
     <tr class="negrita">
                    <td width="10%" align="right"><div class="divcentrar"> </div></td>
                    <td width="20%" align="left"></td>
                    <td width="40%"><div class="divcentrar"></div></td>
                    <td   width="10%"  > </td>
                    <td  width="10%"></td>
                   
            </tr>
            <tr class="negrita">
                    <td width="10%" align="right"><div class="divcentrar"> </div></td>
                    <td width="20%" align="left"></td>
                    <td width="40%"><div class="divcentrar"></div></td>
                    <td   width="10%"  align="right">Total: </td>
                    <td  width="10%" align="right">'.number_format($total,0,'.',',').'</td>
                    
            </tr>
            ';  
$notas = "";
//$html.= '<tr><td colspan="6"></td></tr></table> <p>
//$html.= '</table> <p>';

$html.= '   
        </table> 
        <p>


        <p>
';

// Print text using writeHTMLCell()
$pdf->writeHTML($html, true, false, true, false, '');

// ---------------------------------------------------------

// Close and output PDF document
// This method has several options, check the source code documentation for more information.
 $pdf->Output('imprime_perfil.pdf', 'I');

//============================================================+
// END OF FILE
//============================================================+
?>