<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');
load::lib('tcpdf');
class reporte extends TCPDF {

    

    public function Header() {
      $this->SetFont('helvetica', 'b', 10);
        $titulo = " Union de Productores Organicos Beneficio Majomut, S. DE P.R. DE R.L \n Movimientos al Inventario";
        $this->SetXY(30, 13);
        $this->multiCell(145, 5, $titulo, 0, 'C');

        $this->Image('./img/logo.png', '10', '10', 30, 20, '', '', '', false, 400, '', false, false, 1, false, false, false);   
    }

    public function Footer() {
        /* establecemos el color del texto */
        $this->SetTextColor(0, 0, 0);
        $this->SetFont('helvetica', 'C', 8);
   
            $this->SetXY(10, 265);
            $this->MultiCell(110, 1, "1a. Cerrada de la Era No. 1 Barrio Quinta San Martín C.P. 29247 ", 0, 'C');
            $this->SetXY(120, 265);
            $this->MultiCell(60, 1, "www.majomut.org ", 0, 'C');
            $this->SetXY(182, 265);
            $this->SetFont('helvetica', 'C', 7);
            $this->MultiCell(30, 1, "" . $this->getAliasNumPage() . " / " . $this->getAliasNbPages() . " \n ", 0, 'C');
        
    }

}
$pdf = new reporte($orientation = 'P', $unit = 'mm', $format = 'Letter'); 
ob_end_clean();
// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('');
$pdf->SetTitle('Reporte - Movimientos');
$pdf->SetSubject('');
//================================================================
//VARIABLES POR DECLARAR
$numEvento="PENDIENTE";
//================================================================
//================ SE GENERAN DATOS DE LA POLIZA  ==================

    

// set default footer data
$pdf->SetFooterData('',array(190,190,190),"");

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN,'' , 8));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

//set margins
$pdf->SetMargins(10,30,10);//PDF_MARGIN_LEFT, '20', PDF_MARGIN_RIGHT
$pdf->SetHeaderMargin('5');//PDF_MARGIN_HEADER
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);



//set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

//set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

$pdf->setPageOrientation('P'); // PDF_PAGE_ORIENTATION---> 'L' or 'P'
// ---------------------------------------------------------

// set default font subsetting mode
$pdf->setFontSubsetting(true);

// set default font subsetting mode
$pdf->setFontSubsetting(true);
// Set font
// dejavusans is a UTF-8 Unicode font, if you only need to
// print standard ASCII chars, you can use core fonts like
// helvetica or times to reduce file size.
//$pdf->SetFont('dejavusans', , 8, , true);

// Add a page
// This method has several options, check the source code documentation for more information.
$pdf->AddPage();


// Set some content to print
$html ='<style>
	.negrita{
            font-size: 10px; 
            color: #333;
            font-weight:bold;
	}
        .nonegrita{
            font-size: 10px; 
            color: #333;
            text-align: center; vertical-align: bottom;
        }
        .nonegrita1{
            font-size: 7px; 
            color: #333;
            text-align: center; vertical-align: bottom;
        }
        .divcentrar{
            font-size: 10px; 
            color: #333;
           
        }
        .mitabla{
		font-size: 10px; 
		color: #333; 
	}
        </style>



    
<table align="left" width="100%" border="0">
    
    <thead>
     <tr style="font-size:10px;text-align:left;font-style:italic">
        <td width="20%" align="left" >Desde el dia:  '.strftime("%d-%m-%Y", strtotime($fechaInicial)).'</td>
        <td width="20%" align="center" ></td>
        <td width="20%" align="center" ></td>
        <td width="20%" align="center" ></td>
        <td width="20%" align="center" >Hasta el dia:  '.strftime("%d-%m-%Y", strtotime($fechaFinal)).'</td>
        
      </tr> 
      </thead>
      </table>
      <table align="left" width="100%" border="0">
   <tr class="negrita">
        <td width="10%" align="center"> </td>
        <td  align="center" width="55%"> </td>
        <td  align="center" width="20%"> </td>
        <td  align="center" width="15%"> </td>
    </tr>
    </table>
      <table align="left" width="100%" border="0" cellpadding="2">
    
    <thead>
  <tr style="font-size:10px;text-align:left;font-style:italic">
        <td width="10%" align="left" style="border-top:1px dashed #000000;">Producto</td>
        <td  width="50%" colspan="3" align="center" style="border-top:1px dashed #000000;">Descripción </td>
       <td width="40%" colspan="3" align="center" style="border-top:1px dashed #000000;">Almacen </td>
       
      </tr> 
      <tr style="font-size:10px;text-align:left;font-style:italic">
        <td width="10%" align="left" style="border-bottom:1px dashed #000000;">Fecha</td>
        <td width="20%" align="center" style="border-bottom:1px dashed #000000;">Docto</td>
        <td width="10%" align="center" style="border-bottom:1px dashed #000000;">Lote</td>
        <td width="20%" align="center" style="border-bottom:1px dashed #000000;">T. Movi.</td>
        <td width="20%" align="center" style="border-bottom:1px dashed #000000;">Movimiento</td>
        <td width="10%" align="center" style="border-bottom:1px dashed #000000;">Cantidad</td>
       <td width="10%" align="center" style="border-bottom:1px dashed #000000;">Existencia</td>
      </tr>
      </thead>
      
     
     
      
    
    ';
$clasificacionId="0";

$total=0;
$html.= '
        
            <tr class="negrita">
                    <td width="10%"></td>
                    <td width="50%" colspan="3"></td>
                    <td width="40%" colspan="3"></td>
                    
            </tr>
            ';

foreach ($movimientos as $dato){
    $desProducto=new producto();
    $desProducto=$desProducto->listarJuntoXid($dato->producto_id);
    $html.= '
        
            <tr class="negrita">
                    <td width="10%"><div class="divcentrar">'.$dato->clave.'</div></td>
                    <td width="50%" align="left" colspan="3">'.'  '.$desProducto->descripcion.'</td>
                    <td width="40%" colspan="3"><div class="divcentrar">'.$dato->descripcion_almacen.'</div></td>
                    
            </tr>
            ';
    $movi=new movimiento_inventario();
    $condicion="";
    if($num_movi!="")$condicion=" and ".$num_movi;
        $detalle=$movi->detalleMovimiento($dato->producto_id,$dato->id_almacen,$fechaInicial,$fechaFinal,$condicion,$loteB);
       $subtotal=0;
       $existencia=0;
        foreach ($detalle as $detalleLote){
           
             $concepto=new conceptomovimiento();
             $concepto->listarXid($detalleLote->tipo_movimiento);
             if($concepto->tipo_movimiento=="S"){
                 if($detalleLote->cantidad>0) $detalleLote->cantidad=$detalleLote->cantidad * (-1);
                 else $detalleLote->cantidad=0;
             } 
             $subtotal+=$detalleLote->cantidad;
             if(trim($loteB !='0')){
                
$existencia += ($detalleLote->cantidad );   
             }else{
                 $existencia=$detalleLote->existencia;
             }
        $html.= '
            <tr class="nonegrita1">
                    <td width="10%" align="right">'.strftime("%d-%m-%Y", strtotime($detalleLote->fecha_documento)).'</td>
                    <td width="20%" align="right">'.$detalleLote->referencia.'</td>
                    <td width="10%" align="right">'.$detalleLote->lote.'</td>    
                    <td width="20%"><div class="divcentrar">'.$concepto->tipo_movimiento.'</div></td>
                    <td  align="center" width="20%" align="right" >'.$concepto->descripcion.' </td>
                    <td  width="10%" align="right">'.$detalleLote->cantidad.'</td>
                    <td  width="10%" align="right">'.$existencia.'</td>    
            </tr>
            ';
        } 
        $total+=$subtotal;
      $html.= '
          
<tr class="negrita">
            
                    <td width="10%" align="right"><div class="divcentrar"> </div></td>
                    <td width="20%" align="left"></td>
                    <td width="10%" align="left"></td>
                    <td width="20%"><div class="divcentrar"></div></td>
                    <td  width="20%"  ></td>
                    <td  width="10%"></td>
                    <td  width="10%"><div class="divcentrar" style="font-weight:bold"></div></td>
            </tr>
            <tr class="negrita">
            
                    <td width="10%" align="right"><div class="divcentrar"> </div></td>
                    <td width="30%" colspan="2"></td>
                    <td width="20%"><div class="divcentrar"></div></td>
                    <td  width="20%"  align="right">SubTotal:</td>
                    <td  width="10%" align="right">'.$subtotal.'</td>
                    <td  width="10%"><div class="divcentrar" style="font-weight:bold"></div></td>
            </tr>
            ';  
    
    
}

 $html.= '
     <tr class="negrita">
                    <td width="10%" align="right"><div class="divcentrar"> </div></td>
                    <td width="30%" colspan="2"></td>
                    <td width="20%"><div class="divcentrar"></div></td>
                    <td   width="20%"  > </td>
                    <td  width="10%"></td>
                    <td  width="10%"><div class="divcentrar" style="font-weight:bold"></div></td>
            </tr>
            <tr class="negrita">
                    <td width="10%" align="right"><div class="divcentrar"> </div></td>
                    <td width="30%" colspan="2"></td>
                    <td width="20%"><div class="divcentrar"></div></td>
                    <td   width="20%"  align="right">Total: </td>
                    <td  width="10%" align="right">'.$total.'</td>
                    <td  width="10%"><div class="divcentrar" style="font-weight:bold"></div></td>
            </tr>
            ';  
$notas = "";
//$html.= '<tr><td colspan="6"></td></tr></table> <p>
//$html.= '</table> <p>';

$html.= '   
        </table> 
        <p>


        </p>
';

// Print text using writeHTMLCell()
$pdf->writeHTML($html, true, false, true, false, '');

// ---------------------------------------------------------

// Close and output PDF document
// This method has several options, check the source code documentation for more information.
 $pdf->Output('movimiento.pdf', 'I');   
ob_end_clean();
//============================================================+
// END OF FILE
//============================================================+
?>
