
<?php
View::content();
$anio = date('Y') - 10;
$total=0;
?>
<?php $url = "'" . PUBLIC_PATH . "'"; ?>
<body id="cuerpo_principal">
    <div id="form_container" style="width:100%;" >
<h1><a></a></h1>
    <div id="titulo_superior"> 
        <div id="texto_superior"  >
                 <?php echo "Concentrado de Ventas" ?> 
            </div>
            <div style="text-align:right;margin: 0 0; width:49%; float: left; ">
             <div class='btn'>
                    <?php echo Html::img('inicio.png','cancel','style="text-align:center;width:65px;  padding:5px;"  onclick="window.location = ' . $url . '" ');?>
                </div>  
               
            </div>
    </div>  
<?php echo Form::open("reportes/seguimientoProducto"); ?>  
        <table width="100%" border="0">
            <tr align="center">
                <td>
                    <table width="100%" border="0">
                        <tr style="width:100%;">
                             <td><fieldset style="padding: 15px; height: 100%">
                                   
                                    <table style="width:100%;" border="0">
                                        <tr align="center">
                                            <td  >                
                                                <div class="tres_a">

<?php echo Form::date('fecha_inicial', 'class="element text" required', date('Y-m-d')); ?>
                                                    <br> <label> Periodo Inicial</label>       
                                                </div>
                                            </td>
                                            <td><div class="tres_b">

<?php echo Form::date('fecha_final', 'class="element text" required ', date('Y-m-d')); ?>
                                                    <br>  <label> Periodo Final</label>
                                                </div>

                                            </td>
                                            <td><div class="tres_b">
<?php echo Form::dbSelect("producto","descripcion",array("producto","listarEntrada"),'Seleccione..',' class="element text" style="width:300px" required');?>
                                         <label> Producto</label>
                                                </div>

                                            </td>
                                            <td><div class="tres_b">

<?php echo Form::dbSelect("almacen","descripcion",array("almacen","listar"),' ','  class="element text" style="width:225px"');?>
                                                     <label>Almacen</label>
                                                </div>

                                            </td>
<td><div class="tres_b">

<?php echo Form::dbSelect("lote","codigo",array("lote","listar"),' ','  class="element text" style="width:225px"');?>
                                                     <label>Lote</label>
                                                </div>

                                            </td>
                                            
                                            <td><div class="tres_b">
<?php echo form::submit("MOSTRAR", 'class="CSSButton" '); ?>
                                                    
                                                </div>

                                            </td>
                                        </tr>
                                    </table>
                                      
                                </fieldset></td>
                            
                             
                        </tr>
                       
                        <tr>
                            <td  colspan="3"> 
                                 <fieldset style="padding: 15px; width: 100%;">
                    <legend><b>Datos de la Consulta </b></legend>
     
    <table class=" table table-bordered" >

        <tr  bgcolor="#00984f" align="center">
            <th width="5%">#</th>
            <th width="8%">F. Movi.</th>
            <th width="10%" >Referencia</th>
            <th width="10%" >T. Movimiento.</th>
            <th width="25%" >Producto</th>
            <th width="10%" >Almacen</th>
            <th width="10%" >Lote</th>
            <th width="10%" >Cantidad</th> 
            <th width="10%" >existencia</th>
        </tr>
    </table>
       <div id="contenidoCobrar">  
           <table width="100%" class=" table table-bordered" > 
           <?php 
                            $color="#0174DF";
                            $i=0;
                            $existencia=0;
                            if(isset($resultado))
                            foreach ($resultado as $datos){
                             $i++; 
                             if($color=="#0174DF")
        {
$color="#FFFFFF";
}
else
{
$color="#FFFFFF";
} 
if($datos->tipo_movimiento=='E') $mul=1;
else if ($datos->tipo_movimiento=='S') $mul=-1;

$existencia += ($datos->cantidad * $mul); 
        
        ?>
            <tr valign="center" style="background-color:<?php echo $color ?>">      
            <td width="5%"> <?php echo $i; ?> </td>
            <td width="8%"> <?php echo "  ".$datos->fecha_documento; ?> </td>
            <td width="10%"> <?php echo "  ".$datos->referencia; ?> </td>
            <td width="10%"> <?php echo "  ".$datos->movimiento; ?> </td>
            <td width="25%"> <?php echo "  ".$datos->producto; ?> </td>
            <td width="10%"> <?php echo "  ".$datos->almacen; ?> </td>
            <td width="10%"> <?php echo "  ".$datos->codigo; ?> </td>
            <td width="10%" align="right"><?php echo "  ".number_format($datos->cantidad,2); ?> </td>
            <td width="10%"> <?php echo "  ".number_format($existencia,2); ?> </td>
             </tr>
       
                           <?php 
                            
                           
                           
                          
}    ?>  
             
		</table> </div>
                    
     </fieldset>
                                
                               </td> 
                            
                        </tr>
                        <tr>
                            <td colspan="3" height="50px"></td>
                        </tr>
                        
                    </table>
                </td>
            </tr>
        </table>
<?php echo Form::hidden('codigo', 'class="element text" required ' ); ?>
<?php echo Form::close(); ?>
    </div>


</body>               

<?php ?>

