<?php

?>
    
<br>
<div id="form_container" style="width:100%">
    <h1><a></a></h1>
    <br>
</div>
  <div class="row">
     <div class="col-md-12">
       <h1><a></a></h1>
     </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>
            <span class="glyphicon glyphicon-th"></span>
            <span>Actualizar Lote</span>
         </strong>
        </div>
        <div class="panel-body">
            <?php echo Form::open("catalogo/editarLote/".$lote->id); ?> 
         
            <div class="col-sm-6">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"> #:
                        </div>
<?php echo Form::text( 'lote.id', 'class="form-control"'); ?>

                    </div>
                </div>
            </div> 
             <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Ciclo:
                        </div>
<?php echo Form::text( 'lote.ciclo', 'class="form-control"'); ?>

                    </div>
                </div>
            </div> 
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Num. Lote:
                        </div>
<?php echo Form::text( 'lote.num_lote', 'onblur="combinar()" class="form-control"'); ?>

                    </div>
                </div>
            </div> 
            <div class="col-sm-9">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Codigo:
                        </div>
<?php echo Form::text( 'lote.codigo', 'class="form-control"'); ?>

                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Fecha Caducidad:
                        </div>
<?php echo Form::text( 'lote.fecha_caducidad', 'class="form-control"'); ?>

                    </div>
                </div>
            </div>
             <?php $url ="'" .  PUBLIC_PATH . "catalogo/listadoLote'"; ?>  
            <div class="col-sm-6">
                <div class="form-group">
                   <?php echo Form::button("Cancelar", 'class="btn btn-danger" onclick="window.location = ' . $url . '" '); ?>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                   <button type="submit" name="add_cat" class="btn btn-success">Actualizar</button>  
                </div>
            </div>
            
        <?php echo Form::close(); ?>
        </div>
      </div>
    </div>
    
   </div>

<script>
   function actualizar(){
       window.location.reload();
   }
    function combinar(){
     
       var ciclo = $('#lote_ciclo').val();
       var num_lote = $('#lote_num_lote').val();
       $('#lote_codigo').val(ciclo+"-"+num_lote);
   }
</script> 