<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div id="form_container" style="width:100%">
    <h1><a>Crear</a></h1>
<?php View::partial("formatoTablaCorto",false,array('Encabezado'=>$encabezado,'Model'=>$result,'Campos'=>$campos,'ctrlActualizar'=>"actualizar/",'ctrlAlta'=>"crear/",'ctrleditar'=>"editar/",'ventana'=>"Puesto"));  ?>
</div>
<script>
   function actualizar(){
       window.location.reload();
   }
</script>    
   