<?php View::content(); ?>
<?php Html::includeCss() ?>

<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<section class="why-section spad">
		<div class="container">
			<div class="text-center mb-5 pb-4">
				<h2></h2>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="icon-box-item">
						<div class="ib-icon">
							<i class="flaticon-036-customer-service"></i>
						</div>
						<div class="ib-text">
							<h5>Total Pedidos</h5>
							<p></p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="icon-box-item">
						<div class="ib-icon">
							
                                                        <i class="flaticon-012-24-hours"></i>
						</div>
						<div class="ib-text">
							<h5>Total Ventas</h5>
							<p></p>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="icon-box-item">
						<div class="ib-icon">
							<i class="flaticon-012-24-hours"></i>
						</div>
						<div class="ib-text">
							<h5>Producto mas Vendido</h5>
							<p></p>
						</div>
					</div>
				</div>
			</div>
			
		</div>
	</section>

<br  />
