<?php View::content(); ?>
<div id="form_container" style="width:100%">
    <h1><a></a></h1>
    <br/>
</div>
  
   <div class="row">
    <div class="col-md-5">
       <?php echo Form::open("empresa/editarEmpresa/".$empresa->id); ?>  
        <?php echo Form::hidden( 'empresa.id', 'class="form-control"'); ?>
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>
            <span class="glyphicon glyphicon-th"></span>
            <span>Actualizar Empresa de Envios</span>
         </strong>
        </div>
        <div class="panel-body">
         
            
            <div class="col-sm-11">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Empresa:
                        </div>
<?php echo Form::text('empresa.nombre', ' class="form-control"  required'); ?>

                    </div>
                </div>
            </div> 
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Dirección:
                        </div>
<?php echo Form::text('empresa.direccion', ' class="form-control"  '); ?>

                    </div>
                </div>
            </div> 
            <div class="col-sm-8">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Telefono:
                        </div>
<?php echo Form::text('empresa.telefono', ' class="form-control"  '); ?>

                    </div>
                </div>
            </div> 
            <div class="form-group col-sm-8">
                Datos para Pago
        </div>
            
             <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Banco:
                        </div>
 <?php echo Form::dbSelect("empresa.banco_id", 'nombre_banco', array('bancos', 'datosBanco', 0), '- Seleccione -'," class='form-control ' required  ",$empresa->banco_id);?>

                    </div>
                </div>
            </div>
            <div class="col-sm-11">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Num. Cuenta:
                        </div>
 <?php echo Form::text('empresa.numero_cuenta', ' class="form-control"  '); ?>

                    </div>
                </div>
            </div> 
             
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Clabe Interbancaria:
                        </div>
 <?php echo Form::text('empresa.clabe_interbancaria', ' class="form-control"  '); ?>

                    </div>
                </div>
            </div> 
            
             <?php $url ="'" .  PUBLIC_PATH . "empresa/index'"; ?>  
            <div class="col-sm-6">
                <div class="form-group">
                   <?php echo Form::button("Cancelar", 'class="btn btn-danger" onclick="window.location = ' . $url . '" '); ?>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                   <button type="submit" name="add_cat" class="btn btn-success">Actualizar</button>  
                </div>
            </div>  
             
              
            
        
        </div>
      </div>
        
       
     <?php echo Form::close(); ?>   
    </div>
    
   </div>
  

