<?php View::content(); ?>
<div id="form_container" style="width:100%">
    <h1><a></a></h1>
    <br/>
</div>
  <div class="row">
     <div class="col-md-12">
       
     </div>
  </div>
   <div class="row">
    <div class="col-md-5">
       <?php echo Form::open("empresa/index/"); ?>  
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>
            <span class="glyphicon glyphicon-th"></span>
            <span>Agregar Empresa de Envios</span>
         </strong>
        </div>
        <div class="panel-body">
         
            
            <div class="col-sm-11">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Empresa:
                        </div>
<?php echo Form::text('empresa.nombre', ' class="form-control"  required'); ?>

                    </div>
                </div>
            </div> 
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Dirección:
                        </div>
<?php echo Form::text('empresa.direccion', ' class="form-control"  '); ?>

                    </div>
                </div>
            </div> 
            <div class="col-sm-8">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Telefono:
                        </div>
<?php echo Form::text('empresa.telefono', ' class="form-control"  '); ?>

                    </div>
                </div>
            </div> 
            <div class="form-group col-sm-8">
                Datos para Pago
        </div>
            
             <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Banco:
                        </div>
 <?php echo Form::dbSelect("empresa.bancos_id", 'nombre_banco', array('bancos', 'datosBanco', 0), '- Seleccione -'," class='form-control ' required  ");?>

                    </div>
                </div>
            </div>
            <div class="col-sm-11">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Num. Cuenta:
                        </div>
 <?php echo Form::text('empresa.numero_cuenta', ' class="form-control"  '); ?>

                    </div>
                </div>
            </div> 
             
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Clabe Interbancaria:
                        </div>
 <?php echo Form::text('empresa.clabe_interbancaria', ' class="form-control"  '); ?>

                    </div>
                </div>
            </div> 
             <div class="form-group col-sm-8">
               URL  Rastreo  Envios
        </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Link:
                        </div>
 <?php echo Form::text('empresa.link', ' class="form-control"  '); ?>

                    </div>
                </div>
            </div> 
            <div class="form-group col-sm-8">
               <button type="submit" name="add_cat" class="btn btn-success">Agregar</button>
        </div>  
             
              
            
        <?php echo Form::close(); ?>
        </div>
      </div>
        
       
     <?php echo Form::close(); ?>   
    </div>
    <div class="col-md-7">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong>
          <span class="glyphicon glyphicon-th"></span>
          <span>Lista de Empresas de Envios</span>
       </strong>
      </div>
        <div id="form_container" style="width:100%">   
<?php View::partial("formatoC",false,array('Encabezado'=>$encabezado,'Model'=>$result,'Campos'=>$campos,'ctrleditar'=>"editarEmpresa/",'ctrleliminar'=>"eliminarEmpresa/"));  ?>
</div>
    </div>
    </div>
   </div>
  

