
<?php
View::content();
$anio = date('Y') - 10;
$total=0;
?>
<?php $url = "'" . PUBLIC_PATH . "'"; ?>
<body id="cuerpo_principal">
    <div id="form_container" style="width:100%;" >
<h1><a></a></h1>
    <div id="titulo_superior"> 
        <div id="texto_superior"  >
                 <?php echo "Catalogo de Clientes" ?> 
            </div>
            <div style="text-align:right;margin: 0 0; width:49%; float: left; ">
             <div class='btn'>
                    <?php echo Html::img('inicio.png','cancel','style="text-align:center;width:65px;  padding:5px;"  onclick="window.location = ' . $url . '" ');?>
                </div>  
               
            </div>
    </div>  
<?php echo Form::open("cliente/general"); ?>  
        <table width="100%" border="0">
            <tr align="center">
                <td>
                    <table width="80%" border="0">
                      
                        <tr>
                            <td colspan="3" height="50px"></td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <fieldset style="padding: 15px;">
                                    <legend><b>SALIDA DEL REPORTE :</b></legend>  
<?php $url = "'" . PUBLIC_PATH . "'"; ?>
                                    <table width="100%" border="0">
                                        <tr>
                                            <td style="width:60%;">Titulo</td>
                                            <td style="width:2%;"></td>
                                            <td style="width:18%;"></td>
                                            <td style="width:20%;"></td>
                                        </tr>
                                        <tr>
                                            <td ><?php echo Form::text('titulo', "class='form-control' required"); ?></td>
                                            <td ></td>
                                            <td><?php echo form::submit("IMPRIMIR", 'class="CSSButton" '); ?></td>
                                            <td><?php echo Form::button("CANCELAR", 'class="CSSButton" onclick="window.location = ' . $url . '" '); ?>   </td>
                                        </tr>
                                    </table>
                                </fieldset>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
<?php echo Form::close(); ?>
    </div>


</body>               

<?php ?>
