
<?php
error_reporting(E_ALL ^ E_NOTICE);
View::template(null);
Load::lib('funciones');
 $pdf = new TCPDF($orientation = 'P', $unit = 'mm', $format = 'Letter');


// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('SISTEMA');
$pdf->SetTitle('forma de pago');
$pdf->SetSubject('');
//================================================================
//================ SE GENERAN DATOS DEL AVISO  ==================
//PARA VISULAIZAR UN MES EN ESPANIOL
//setlocale(LC_ALL,"es_ES@euro","es_ES","esp");


// set default header data
//$pdf->SetHeaderData($logo,30, $titulo, '', "\n" , '', array(190, 190, 190));

//Para que no se imprima el encabezado del PDF.
$pdf->setPrintHeader(false);
//$pdf->setPrintFooter(false);
// set default footer data
//$pdf->SetFooterData('', array(190, 190, 190), $usuarioCaptura);
$pdf->SetFooterData('',array(190,190,190),"Teléfonos 967 678 31 96 y 967 678 81 06 \ www.majomut.org \ mail: ventas@majomut.org \  info@majomut.org"." "."");
// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', 8));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

//set margins (15,20,15)
$pdf->SetMargins(10, 10, 10); //PDF_MARGIN_LEFT, '20', PDF_MARGIN_RIGHT
$pdf->SetMargins(10,10,10);//PDF_MARGIN_LEFT, '20', PDF_MARGIN_RIGHT
$pdf->SetHeaderMargin('10');//PDF_MARGIN_HEADER
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));


//set auto page breaks
//$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

//set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);


// ---------------------------------------------------------
// set default font subsetting mode
$pdf->setFontSubsetting(true);

// set default font subsetting mode
$pdf->setFontSubsetting(true);
// Set font
// dejavusans is a UTF-8 Unicode font, if you only need to
// print standard ASCII chars, you can use core fonts like
// helvetica or times to reduce file size.
//$pdf->SetFont('dejavusans', , 8, , true);
// Add a page
// This method has several options, check the source code documentation for more information.
$pdf->AddPage();

$fechaImpresion = date("d/m/Y H:i:s");


//$filename = $PNG_TEMP_DIR . '/home/nerito/prod/temporalXml.png';
//$filename = $PNG_TEMP_DIR.'temporalXml.png';

$matrixPointSize = 10;
$errorCorrectionLevel = 'L';


/*

$datosRecibo = Load::model('recibos')->datosRecibo($id);
foreach ($datosRecibo as $dato) {
    $idSujeto = $dato->cat_sujetos_contribuyentes_id;
    $num_recibo = $dato->num_recibo;
    $fecha = $dato->fecha_hora;
    $documento = strftime("%d-%m-%Y", strtotime($dato->fecha_documento)); 
    $idCobro = $dato->cobros_id;
    $comentarios = $dato->comentarios;
    $monto = $dato->monto;
    $tRecargo = $dato->recargo;
    $fechaI = strftime("%d-%m-%Y", strtotime($dato->fecha_hora));
} 

 */


$html2="";
// Set some content to print
$html = '<style>
	table.first {
        color: #003300;
        font-family: helvetica;
        font-size: 8pt;
        top: -100px; 
    }
    table.second {
        color: #003300;
        font-family: helvetica;
        font-size: 8pt;
        top: 10px; 
    }
   
    table.thirty {
        color: #003300;
        font-family: helvetica;
        font-size: 6pt;
        top: -100px; 
    }
    table.four {
        color: #003300;
        font-family: helvetica;
        font-size: 15pt;
        top: -100px; 
    }
        p.first {
        color: #003300;
        font-family: helvetica;
        font-size: 10pt;
        text-align: center;
        font-weight: bold;
    }
    .estilo1{
		font-size: 10px; 
		color: #333; 
	}
        .estilo2{
		font-size: 12px; 
		color: #333; 
	}
        </style>';

//$html.= '<p class="first">'.$nombreEmisor.'</p>';


$html .='<table width="100%" border="0" class="estilo1">
      <tr>
        <td width="10%" rowspan="3">&nbsp;</td>
        <td width="40%">Catalogo de Clientes</td>
        <td width="10%">&nbsp;</td>
        <td width="40%"><div align="right">'.  FechaCadena(date('Y-m-d')).'</div></td>
      </tr>
      <tr>
        <td>'.$titulo.' </td>
        <td>&nbsp;</td>
        <td><p align="right">'.date('H:i:s').' '.date('A').'</p>
          </td>
      </tr>
      <tr>
        <td></td>
        <td>&nbsp;</td>
        <td><p align="right"></p></td>
      </tr>
      <tr bgcolor="#000" style="font-size:2px; height="2px";">
              <td colspan="4"><b></b></td>
            </tr>
    </table>';
    
    $html .='<table class="estilo1" border="0" width="100%" cellpadding="1">
        
       ';
    
    
    foreach ($resultado as $datos) {
        $i++;
        if($color=="#FFF")
        $color="#F8F8F8";
        else 
        $color="#FFF";   
            $arreglod[] = "";
$arreglod[0] = $datos->calle;$arreglod[1] = $datos->numeroexterior;$arreglod[2] = $datos->numerointerior;
$arreglod[3] = $datos->colonia;$arreglod[4] = $datos->municipio;$arreglod[5] = $datos->estado;
$arreglod[6] = $datos->pais;$arreglod[7] = $datos->codigopostal;
$arreglod = array_filter($arreglod, "strlen");
        $html .= '<tr>
    <td width="40%"><b>Nombre:</b> '.$datos->nombrecompleto.'</td>
        <td width="20%"><b>R.F.C.:</b> '.$datos->rfc.'</td>
	<td width="20%"><b>[</b> '.(($datos->tipoente=="F")?'Fisica':(($datos->tipoente=="M")?'Moral':'')).' <b>]</b></td>
    <td width="20%"><b>[</b> '.$datos->clave.' <b>]</b></td>
  </tr>
  
  <tr>
    <td colspan="4"><b>Direccion:</b> '.implode(", ", $arreglod).'</td>
    
  </tr>
  <tr>
    <td colspan="2"><b>Forma de pago:</b>'.$datos->concepto.'</td>
    <td ><b>Metodo de pago:</b> '.(($datos->credito=="Credito")?'Si':'Contado').' </td>
	<td ><b>Dias Credito:</b> '.$datos->dias.'</td>
            
  </tr>

  <tr>
    <td ><b>Telefono:</b> '.$datos->telefono.'</td>
    <td colspan="2"><b>Correo:</b> '.$datos->correoelectronico.'</td>
     <td ><b>Estatus:</b> '.(($datos->estatus=="1")?'Activo':'Inactivo').' </td>   
  </tr>
  
  
  <tr bgcolor="#000" style="font-size:1px; height="1px";">
              <td colspan="4"></td>
            </tr>
                ';
       $subtotalV=0; $ivaV=0;$totalCobroV=0;
       $subtotal=0; $iva=0;$totalCobro=0;
      if($detalleDatos->estado=="Activo") {
      $subtotal +=  $detalleDatos->subtotal;
      $iva +=  $detalleDatos->iva;
      $totalCobro +=  $detalleDatos->monto;
      if($detalleDatos->venta=='1'){
      $subtotalV +=  $detalleDatos->subtotal;
      $ivaV +=  $detalleDatos->iva;
      $totalCobroV +=  $detalleDatos->monto;
      } 
      }  
    }
  $html .='</table> <br><br>'; 
    
  
    
   


$html .='
    <br>  

';
echo $html;
ob_end_clean();    
// Print text using writeHTMLCell()
$pdf->writeHTML($html, true, false, true, false, '');

// ---------------------------------------------------------
// Close and output PDF document
// This method has several options, check the source code documentation for more information.
ob_end_clean(); 
$pdf->Output('recibo.pdf', 'I');
 

//============================================================+
// END OF FILE
//============================================================+

?>