<?php $url = "'" . PUBLIC_PATH . "cliente/'"; ?>
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


echo $msj;


?>
<table style="width: 100%; text-align: center;">
<?php
      
    
      echo ' <tr>
            <td>';
        echo Form::button("Regresar", 'class="btn btn-danger" onclick="window.location = ' . $url. '" '); 
        echo '</td>
            
        </tr>';
      
     echo'</table>';  
    ?>