<?php Tag::css('demo_page'); ?>
<?php Tag::css('demo_table'); ?>
<?php Html::includeCss() ?>
<?php echo Tag::js('jquery.dataTables.min'); ?>
<?php
View::content();
?>

<div id="container" >
    <br/>
    <div id="form_container" style="width:100%;" >
        <h1 class="lineaSuperior"><a></a></h1>
        <div class="form_description">
            <h2>Listado de Clientes</h2><br>
        </div>
        <br/>
        <ul class="nav nav-tabs">
            <br>
            <li class="active">
                <a href="#home"   data-toggle="tab"    >Clientes Activos</a>
            </li>
            <li class="">
                <a href="#organismos" class="menuSolicitud"    data-tipo="organismos"  >Clientes Inactivos</a>
            </li>

        </ul>

        <div class="tab-content" id="myTabContent">
            <div class="tab-pane   active" id="home"  aria-labelledby="home-tab">
                <div id="dt_example" style="margin:0 auto; padding:10px 20px; background-color:#ffffff; ">      
                   
                    
                                 <div class="row">
                             <div class="col-md-12">
                                   <div style="text-align:right;margin: 0 0; width:100%; float: left; ">
                <div class='btn'>
                    <?php                                      
                          echo Html::linkAction('crear',Html::img('nuevo.png','cancel','style="text-align:center;width:75px;  padding:2px;"'),'');                 
                    ?>
                    <?php                                      
                          echo Html::linkAction('importar',Html::img('importar.png','cancel','style="text-align:center;width:75px;  padding:2px;"'),'');                 
                    ?>
                </div>
            </div> 
 
 <table  border="0" width="100%" id="display" >
            <thead>
                <tr  style="font-size: 9px;letter-spacing: -0.8px;">
                    <th width='5%'> #</th>
                    <th width='15%'> Clave</th>
                    <th width='30%'> Nombre / Razón Social</th>
                    <th width='30%'>R.F.C.</th>                              
                    <th width='13%'>E-mail</th>
                    <th width='13%'>Telefono</th>
                    <th width='13%'>Acción</th>
                    </tr>
            </thead>
            <tbody>
<?php

           $i=1;
            foreach($cliente as $res){

              
                       echo "<tr>";
                        echo "<td>".$res->id."</td>";
                        echo "<td>".$res->clave."</td>";
                            echo "<td>".$res->nombrecompleto."</td>";
                            echo "<td>".$res->rfc."</td>";
                            echo "<td>".$res->correoelectronico."</td>"; 
                            echo "<td>".$res->telefono."</td>"; 
                            echo "<td>";
                            if($res->id !=1){
                            echo Html::linkAction("editar/" . $res->id,'<span class="glyphicon glyphicon-edit"></span>','class="btn btn-info btn-xs"  title="Editar" data-toggle="tooltip"');
                            echo Html::linkAction("bloquear/" . $res->id, Html::img('bloquear.png', 'cancele', 'style="text-align:center;width:25px;padding:2px;" title="Bloquear Registro "'), ('onclick="return confirm(\'Está Seguro que desea dar de baja?\')"'));        
                            }
                            echo "</td>";
                            echo "</tr>";  
                             
                        $i++; 
               }
            ?>
            </tbody>
        </table>
        </div>     
                                 </div>
                       
                </div>
            </div>
            <div class="tab-pane" id="organismos"  aria-labelledby="organismos-tab">
                  <div id="dt_example" style="margin:0 auto; padding:10px 20px; background-color:#ffffff; ">      
        <br />
        <div style="text-align:center; width:100%;">
            
            <br /><br />
        </div>
        <table  border="0" width="100%" id="display" class="display">
            <thead>
                <tr  style="font-size: 9px;letter-spacing: -0.8px;">
                    <th width='5%'> #</th>
                    <th width='30%'> NOMBRE</th>
                    <th width='30%'>RFC</th>
                    
                   
                    <th width='13%'>E-MAIL</th>
                    <th width='13%'>TELEFONO</th>
                    <th width='13%'>F. BAJA</th>
                    <th width='13%'>ACCION</th>
                    </tr>
            </thead>
            <tbody>
<?php

           $i=1;
            foreach($result as $res){

              
                       echo "<tr>";
                        echo "<td>".$res->id."</td>";
                            echo "<td>".$res->nombre."</td>";
                            echo "<td>".$res->rfc."</td>";
                            echo "<td>".$res->correo."</td>"; 
                            echo "<td>".$res->telefono."</td>"; 
                            echo "<td>".$res->fecha_baja."</td>"; 
                            echo "<td>";
                           echo Html::linkAction("activar/" . $res->id, Html::img('desbloquear.png', 'cancel', 'style="text-align:center;width:32px;padding:2px;"'), ('onclick="return confirm(\'Está Seguro que desea activarlo?\')"'));
                            echo "</td>";
                            echo "</tr>";  
                             
                        $i++; 
               }
            ?>
            </tbody>
        </table>
        
       
    </div>
            </div>
            <br/>
        </div>

       

    </div>
</div>

<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
    $(".menuSolicitud").on("click", comprobarEstado);
    function comprobarEstado() {
        var tipo = $(this).data("tipo");
        var elemento = $(this);

        if (tipo == "organismos") {

            $('a[href="#organismos"]').attr('data-toggle', 'tab');
            $('a[href="#organismos"]').tab('show');

        }


    }
</script>    
<script type="text/javascript" charset="utf-8">
    $(function() {
        $("#display").dataTable({ 
            "aaSorting": [[0,"asc"]],
            "bAutoWidth": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "aProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encuentran resultados",
                "sInfo": "Mostrando desde _START_ hasta _END_ registros",
                "sInfoEmpty": "Mostrando desde 0 hasta 0 de 0 registros",
                "sInfoFiltered": "(filtrando de _MAX_ registros en total)",
                "sSearch": "Buscar",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sPrevious": "Anterior",
                    "sNext": "Siguiente",
                    "sLast": "Ultimo"
                }
            }
        });
    });
    
</script>