
<?php
View::content();
$anio = date('Y') - 10;
$total=0;
?>
<?php $url = "'" . PUBLIC_PATH . "'"; ?>
<body id="cuerpo_principal">
    <div id="form_container" style="width:100%;" >
<h1><a></a></h1>
    <div id="titulo_superior"> 
        <div id="texto_superior"  >
                 <?php echo "Reporte por Tipo de Pago" ?> 
            </div>
            <div style="text-align:right;margin: 0 0; width:49%; float: left; ">
             <div class='btn'>
                    <?php echo Html::img('inicio.png','cancel','style="text-align:center;width:65px;  padding:5px;"  onclick="window.location = ' . $url . '" ');?>
                </div>  
               
            </div>
    </div>  
<?php echo Form::open("cliente/tipoCliente"); ?>  
        <table width="100%" border="0">
            <tr align="center">
                <td>
                    <table width="90%" border="0">
                        <tr style="width:100%;">
                             
                            
                             <td>
                             
                             <fieldset style="padding: 15px; height: 100px">
                                    <legend><b>GENERAR REPORTE :</b></legend> 
                                    <table width="100%" border="0">
                                        <tr>
                                            <td>Tipo Cliente</td>
                                            
                                            <td><?php $tipo_valor = array("F" => "Persona Fisica", "M" => "Persona Moral");
                                    echo Form::Select("tipo_cliente", $tipo_valor, "class='form-control' required "); ?></td>
                                            <td width="2%"></td>
                                                <td><?php echo form::submit("MOSTRAR", 'class="CSSButton" '); ?></td>
                                        
                                        </tr>
                                    </table>
                                </fieldset>
                                 <br>
                             </td>
                        </tr>
                       
                        <tr>
                            <td  colspan="3"> 
                                 <fieldset style="padding: 15px; width: 100%;">
                    <legend><b>Datos de la Consulta </b></legend>
     
    <table width="100%" border="0" class="table table-bordered">

        <tr  bgcolor="#00984f" align="center">
            <th width="5%">#</th>
            <th width="10%">Clave</th>
            <th width="10%" >Nombre</th>
            <th width="10%" >R.F.C.</th>
             <th width="30%" >Direccion</th>
             <th width="10%" >Telefono</th>
              <th width="15%" >Correo</th>        
        </tr>
    </table>
       <div id="contenidoCobrar">  
        <table width="100%" border="0" align="center" class="arqueo"> 
           <?php 
                            $color="#0174DF";
                            $i=0;
                            if(isset($resultado))
                            foreach ($resultado as $datos){
                             $i++; 
                             if($color=="#0174DF")
        {
$color="#FFFFFF";
}
else
{
$color="#FFFFFF";
} 
        $arreglod[0] = $datos->calle;$arreglod[1] = $datos->numeroexterior;$arreglod[2] = $datos->numerointerior;
$arreglod[3] = $datos->colonia;$arreglod[4] = $datos->municipio;$arreglod[5] = $datos->estado;
$arreglod[6] = $datos->pais;$arreglod[7] = $datos->codigopostal;
$direccion=implode(", ", $arreglod);
        ?>
            <tr valign="center" style="background-color:<?php echo $color ?>">      
            <td width="5%"> <?php echo $i; ?> </td>
            <td width="10%"> <?php echo "  ".$datos->clave; ?> </td>
            <td width="10%"> <?php echo "  ".$datos->nombrecompleto; ?> </td>
            <td width="10%"> <?php echo "  ".$datos->rfc; ?> </td>
            <td width="30%"> <?php echo "  ".$direccion; ?> </td>
             <td width="10%" align="right"><?php echo "  ".$datos->telefono; ?> </td>
            <td width="15%" align="right"> <?php echo "  ".$datos->correoelectronico; ?> </td>
            
             </tr>
       
                           <?php 
                           if($datos->estado=="Activo") 
                           $total = $total + $datos->monto;
                           
                          
}    ?>  
             
		</table> </div>
                    <table  width="100%" border="0"  class="arqueo">
                    <tr height="50px">
              <td colspan="4" width="89%" align="right"> Total : $ </td>
              <td width="10%" align="right">  <?php echo "  ".number_format($total,2); ?> </td> 
            <td width="1%" align="right">  </td> 
             </tr>
		</table>
     </fieldset>
                                
                               </td> 
                            
                        </tr>
                        <tr>
                            <td colspan="3" height="50px"></td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <fieldset style="padding: 15px;">
                                    <legend><b>SALIDA DEL REPORTE :</b></legend>  
<?php $url = "'" . PUBLIC_PATH . "'"; ?>
                                    <table width="100%" border="0">
                                        <tr>
                                            <td style="width:60%;">Titulo</td>
                                            <td style="width:20%;"></td>
                                            <td style="width:20%;"></td>
                                        </tr>
                                        <tr>
                                            <td ><?php echo Form::text('titulo', ""); ?></td>
                                            <td><?php echo form::submit("IMPRIMIR", 'class="CSSButton" '); ?></td>
                                            <td><?php echo Form::button("CANCELAR", 'class="CSSButton" onclick="window.location = ' . $url . '" '); ?>   </td>
                                        </tr>
                                    </table>
                                </fieldset>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
<?php echo Form::close(); ?>
    </div>


</body>               

<?php ?>
