<script>
 function imprime_lista()
{
     var almacen= $("#combinacion_almacen_id").val();
var operacion='MOSTRAR_LISTA_COM' 
$.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'inventario/libreriaInventario/'; ?>",
          data: "operacion=" + operacion+"&almacen=" + almacen,
          success: function(html){
            $("#resultado").html(html);
          }
        });
    
}   

</script>    
<?php View::content(); ?>
<body id="cuerpo_principal">

<div id="form_container" style="width:100%;" >
    <br>
    <h1><a></a></h1>
    <div id="titulo_superior"> 
        <div id="texto_superior"  >
                 <?php echo "Combinacion de lotes" ?> 
            </div>
            
    </div>
    <?php echo Form::open("inventario/crearCombinacion"); ?>
 <?php echo Form::hidden("vale.id"); ?>

   
    
    <div id="margen" >
  <div class="form-row">
    
    
     <?php echo Form::hidden('combinacion.tipo_documento', 'maxlength="20" required class="form-control"   ',"COMBINACION LOTE(S)"); ?>
      
    
      <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Almacen:    
                            </div>
                            <?php
                             echo Form::dbSelect("combinacion.almacen_id", "descripcion", array("almacen", "listar"), 'Seleccione..', 'class="form-control" onchange="imprime_lista()" '); 
                            ?>
                        </div>
                    </div> 
                </div>
    <div class="col-sm-5">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Documento:    
                            </div>
                          <?php echo Form::text('combinacion.documento', ' readonly="readonly" maxlength="20" required class="form-control"   ',$num); ?>
                    </div>
                </div> 
    </div>
      <div class="col-sm-3">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Fecha :    
                            </div>
                          <?php echo Form::text('combinacion.documento', ' readonly="readonly" maxlength="20" required class="form-control"   ',date('d-m-Y')); ?>
                    </div>
                </div> 
    </div>
  </div>
   <div class="col-sm-6">
             <div class="panel panel-success">
        <div class="panel-heading">Porductos y Lotes Existentes</div>
        <div class="panel-body">
             <div class="form-row">
               
                 
                   

             
            <div id="resultado" style=" width: 100%; height: 300px; border-bottom:1px;  border-bottom-color:#000; "> </div>
        
          </div>
        
        </div>
             </div>  
        
   </div>
   <div class="col-sm-6">
    <div class="panel panel-success">
        <div class="panel-heading">Lotes Existentes</div>
        <div class="panel-body">
             <div class="form-row">
                <div class="col-md-2 ">
      <label for="validationCustomUsername">cantidad</label>
      <div class="input-group">
        
        <?php echo Form::number('vale.cantidad', '  '); ?>
        
      </div>
    </div> 
                 <div class="col-md-3 mb-3">
      <label for="validationCustomUsername">Producto</label>
      <div class="input-group">
        
       <?php echo Form::dbSelect("vale.producto_id","descripcion",array("producto","listarEntrada"),'Seleccione..',' class="form-control"');?>
        
      </div>
    </div> 
                  
                 <div class="col-md-2 mb-3">
      <label for="validationCustomUsername">Lote</label>
      <div class="input-group">
        <div  id="loteProducto" >
       <?php echo Form::dbSelect("lote","codigo",array("lote","listar"),'Seleccione..','class="form-control" ');?>
        </div>
      </div>
    </div> 
                  
       <div class="col-md-3 mb-3">
      <label >Almacen</label>
      <div class="input-group">
        <div id="almacen">
      <?php echo Form::dbSelect("vale.almacen_id","descripcion",array("almacen","listar"),'Seleccione..','class="form-control" ');?>
        </div>
      </div>
    </div> 
                 <div class="col-md-2 mb-3">
      <label >.</label>
      <div class="input-group">
        <?php echo Form::button("Agregar","id='Agregar' style='width:98%;' class='btn-success btn' ")?>
      </div>
    </div> 
                 
             </div>      

             
            <div id="resultado" style="height: 200px; border-bottom:1px;  border-bottom-color:#000; "> <?php print"<script> imprime_lista() </script>"; ?></div>
        </br>
          
        <table style="width: 100%" border="0">
                
                     <tr >
      <td>Observaciones:</td>
      <td><?php echo Form::textarea('vale.observacion', '  class="form-control"  '); ?></td>
    
                 </tr>
             </table>
        <br>
       
        <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Entrego:    
                            </div>
                          <?php echo Form::text('vale.capturo', ' required class="form-control"   '); ?>
                    </div>
                </div> 
    </div>
       <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Recibio:    
                            </div>
                          <?php echo Form::text('vale.recibio', ' required class="form-control"   '); ?>
                    </div>
                </div> 
    </div>
      <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Valido:    
                            </div>
                          <?php echo Form::text('vale.valido', ' required class="form-control"   '); ?>
          </div>
                </div> 
    </div>
        </div>
             </div>
   </div>    
        
            <?php $url = "'" . PUBLIC_PATH . "inventario/listadoRecepcion'"; ?>
        <table width="100%">
        <tr align="center">
            <td width="33%">     
            <?php echo Form::button("Cancelar", 'class="btn btn-lg btn-danger" onclick="window.location = ' . $url . '" '); ?>
            </td>
            <td>
           
            </td>
            <td width="33%">
            <?php echo Form::submit((($accion == 'crearRecepcion') ? 'Guardar' : 'Actualizar'), 'type="submit" class="btn btn-lg btn-primary"'); ?>       
            </td>
        </tr>
     </table>
      
  </div> 
</div>
    </br>
<?php echo Form::close(); ?>

</body>

<script type="text/javascript">
           $("#vale_producto_id").change(function(){
	buscaAlmacen();
        buscaDetalle();
});
 $("#vale_proveedor_id").change(function(){
	buscaProveedor();
        
});

$("#Agregar").click(function(){
	
            agregarPartida();
  
});
</script>  
 


       
                        

