<script type="text/javascript">
    function imprime_lista()
{
var operacion='MOSTRAR_LISTA' 
$.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'inventario/libreriaInventario/'; ?>",
          data: "operacion=" + operacion,
          success: function(html){
            $("#resultado").html(html);
          }
        });
    
}   
    function buscaProducto() {
        var almacenId = $('#traspaso_almacen_id').val();

        var operacion = "BUSCA_PRODUCTO";
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "almacenId=" + almacenId + "&operacion=" + operacion,
            success: function (html) {
                $("#productoEs").html(html);
            }
        });
    }
    function buscaLote() {
        var almacenId = $('#traspaso_almacen_id').val();
        var productoId = $('#venta_producto_id').val();
        var operacion = "BUSCA_LOTE_PA";
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "almacenId=" + almacenId + "&productoId=" + productoId + "&operacion=" + operacion,
            success: function (html) {
                $("#loteProducto").html(html);
            }
        });
    }
    
    function buscaExistencia() {
        var lote = $('#lote').val();
        var producto = $('#venta_producto_id').val();
        var almacen = $('#traspaso_almacen_id').val();
        var operacion = "BUSCA_EXISTENCIA_LS";
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'inventario/libreriaInventario/'; ?>",
            data: "lote=" + lote + "&producto=" + producto+ "&almacen=" + almacen  + "&operacion=" + operacion,
            success: function (html) {
                $("#existencia").val(html);
            }
        });
    }
   
    function buscaDetalle()
    {
        var productoId = $('#venta_producto_id').val();
        var operacion = 'MOSTRAR_DETALLE'
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'inventario/libreriaInventario/'; ?>",
            data: "productoId=" + productoId + "&operacion=" + operacion,
            success: function (html) {
                html = "lote";
                html = html.replace(/^\s+|\s+$/g, "");
                $('#opcion').val(html);
                if (html == "lote") {
                    $('#loteProducto').show();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').hide();
                    $('#serie').val('');
                    $('#numInventario').val('');

                } else if (html == "serie") {
                    $('#loteProducto').hide();
                    $('#serieProducto').show();
                    $('#inventarioProducto').hide();
                    $('#numInventario').val('');
                    $('#lote').val('');
                } else if (html == "loteInventario") {
                    $('#loteProducto').show();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').show();
                    $('#serie').val('');
                } else if (html == "serieInventario") {
                    $('#loteProducto').hide();
                    $('#serieProducto').show();
                    $('#inventarioProducto').show();
                    $('#lote').val('');
                } else if (html == "soloInventario") {
                    $('#loteProducto').hide();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').show();
                    $('#lote').val('');
                    $('#serie').val('');
                } else {
                    $('#inventarioProducto').hide();
                    $('#loteProducto').hide();
                    $('#serieProducto').hide();
                    $('#serie').val('');
                    $('#lote').val('');
                    $('#numInventario').val('');

                }
                //  $("#detalleProducto").html(html);
            }
        });

    }
    function buscaUnidadPrecio() {
        var productoId = $('#venta_producto_id').val();

        var operacion = "BUSCA_UNIDADPRECIO";
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "productoId=" + productoId + "&operacion=" + operacion,
            success: function (html) {

                separador = ","
                cadena = html.split(separador)
                $("#etiqueta").html(cadena[0]);
                var valor = cadena[1];
                $("#venta_precio").val(valor);
                 buscaLote();
        buscaDetalle();
            }
        });
    }
    
    function agregarPartida() 
{
    
var operacion='AGREGAR_PARTIDAF';	
var cantidad 	=	$('#venta_cantidad').val();
var productoId 	=	$('#venta_producto_id').val();
var almacenId 	=	$('#traspaso_almacen_id').val();
var serie="";
var lote 	=	$('#lote').val();
var opcion='lote'
var mens="";
var re = /,/g;
cantidad=cantidad.replace(re,"");

	if (cantidad=="") {mens+="\n- Inserte una cantidad valida";}
        if (productoId=="") {mens+="\n- Elija un producto";}
        if (almacenId=="") {mens+="\n- Elija un almacen";}
        if(opcion=='lote'){
        if (lote=="") {mens+="\n- Indique el numero de Lote";}
        
        if (lote=="") {mens+="\n- Indique el numero de Lote";}
        
        }
        

if (mens!=""){
     alert('Verifique los siguientes campos:\n'+mens);
		
}else
	{
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'inventario/libreriaInventario/'; ?>",
          data: 'operacion=' + operacion + '&cantidad=' + cantidad+"&productoId=" + productoId+"&almacenId=" + almacenId+"&lote=" + lote+"&serie=" + serie+"&opcion=" + opcion,
         
            success: function(html){
        
        html=html.replace(/^\s+|\s+$/g, "");
      if (html=='Si'){
           alert('Esta partida ya existe.......!');
      }else{
         
          imprime_lista();
          	$('#venta_cantidad').val("");
	$('#venta_producto_id').val("");
	$('#venta_precio').val("");

	$('#lote').val("");
        $('#existencia').val("");
      }
          }
             });
	}
}

    function quitar_partida(linea)
{
    
        var operacion='QUITAR_PARTIDA' 
var linea=linea;

$.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'inventario/libreriaInventario/'; ?>",
          data: "operacion=" + operacion + "&linea="+ linea,
          success: function(html){
         imprime_lista();
          }
        });
   

}
    
    
    function buscarOrigen(){
         var almacen= $("#traspaso_almacen_id").val();
         var concepto = $("#traspaso_almacen_id option:selected").text()
         if(almacen >= 1){
         $("#traspaso_origen").val(concepto); 
         buscaProducto();
        }else{
            $("#traspaso_origen").val("");
        }
        
    }
</script>    
<?php View::content(); ?>
<body id="cuerpo_principal">

    <div id="form_container" style="width:100%;" >
        <br>
        <h1><a></a></h1>
        <div id="titulo_superior"> 
            <div id="texto_superior"  >
                <?php echo "Ajustes al Inventario" ?> 
            </div>
            <div style="text-align:right;margin: 0 0; width:49%; float: left; ">
                <div class='btn'>
                    <?php
                  //  echo Html::linkAction('listadoVenta', Html::img('verLista.png', 'cancel', 'style="text-align:center;width:90px;  padding:2px;"'), '');
                    ?>
                </div>
            </div>
        </div>
        <?php echo Form::open("inventario/" . $accion); ?>
        <?php echo Form::hidden("traspaso.id"); ?>



        <div id="margen" >
            <div class="form-row">


                <?php echo Form::hidden('traspaso.tipo_documento', 'maxlength="20" required class="form-control"   ', "AJUSTE"); ?>

                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">  Almacen :    
                            </div>
                            <?php
                             echo Form::hidden('traspaso.origen',' class="form-control" ');
                             echo Form::dbSelect("traspaso.almacen_id", "descripcion", array("almacen", "listar"), 'Seleccione..', 'required class="form-control" onchange="buscarOrigen()" '); 
                            ?>
                        </div>
                    </div> 
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Documento:    
                            </div>
<?php echo Form::text('traspaso.documento', ' readonly="readonly" maxlength="20" required class="form-control"   ', $num); ?>
                        </div>
                    </div> 
                </div>

                <div class="col-sm-3">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Fecha:    
                            </div>
<?php echo form::date('traspaso.fecha_documento', 'placeholder="dd-mm-aa" required class="form-control"', date('Y-m-d')); ?>
                        </div>
                    </div> 
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Movimiento Ajuste:    
                            </div>
                            <?php
                            echo Form::dbSelect("destino_id", "descripcion", array("concepto", "listarM", '0'), 'Seleccione..', 'class="form-control"  required'); 
                            ?>
                                                   </div>
                    </div> 
                </div>


            </div>
           
            <div class="panel panel-primary">
                <div class="panel-heading">Datos Producto </div>
                <div class="panel-body">
                    <div class="form-row">
                        <div class="col-md-3 ">
                            <label for="validationCustomUsername">Producto</label>
                            <div class="input-group">
<div id="productoEs">
<?php echo Form::text("venta.producto_id", ' class="form-control"'); ?>
</div>
                            </div>
                        </div> 
                        
                        <div class="col-md-2 ">
                            <label >Lote</label>
                            <div class="input-group">
                                <div  id="loteProducto" >

                                    <?php echo Form::text("lote",  'class="form-control" '); ?>
                                </div>
                            </div>
                        </div> 

                         
                        <div class="col-md-2 ">
                            <label >precio</label>
                            <div class="input-group">
                                <div id="almacen">
<?php echo Form::text("venta.precio",  'class="form-control" '); ?>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-2 ">
                            <label >cantidad</label>
                            <div class="input-group">

<?php echo Form::number('venta.cantidad', ' class="form-control"  min="0" step="0.1"', '0'); ?>

                            </div>
                        </div> 


                        <div class="col-md-1 ">
                            <label >.</label>
                            <div class="input-group">
                                <div  id="etiqueta" >

                                </div>
                            </div>
                        </div> 






                        
                        <div class="col-md-1 ">
                            <label >existencia</label>
                            <div class="input-group">
                                <div id="almacen">
<?php echo Form::text("existencia",  'class="form-control" readonly="readonly"'); ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-1 ">
                            <label >.</label>
                            <div class="input-group">
<?php echo Form::button("Agregar", "id='Agregar' style='width:98%;' class='btn-success btn' ") ?>
                            </div>
                        </div> 

                    </div>      
                    <br>

                    <div id="resultado" style="height: 200px; border-bottom:1px;  border-bottom-color:#000; "> <?php print"<script> imprime_lista() </script>"; ?></div>
        </br>
          
        <table style="width: 100%" border="0">
                
                     <tr >
      <td>Observaciones:</td>
      <td><?php echo Form::textarea('traspaso.observacion', '  class="form-control"  '); ?></td>
    
                 </tr>
             </table>
        <br>
       
       
      <div class="col-sm-8">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Valido:    
                            </div>
                          <?php echo Form::text('traspaso.valido', ' required class="form-control"   '); ?>
          </div>
                </div> 
    </div>



<?php $url = "'" . PUBLIC_PATH . "'"; ?>
    <table width="100%">
        <tr align="center">
            <td width="33%">     
<?php echo Form::button("Cancelar", 'class="btn btn-lg btn-danger" onclick="window.location = ' . $url . '" '); ?>
            </td>
            <td>

            </td>
            <td width="33%">
<?php echo Form::submit('Guardar', 'type="submit" class="btn btn-lg btn-primary"'); ?>       
            </td>
        </tr>
    </table>

</div> 
</div>
</br>
<?php echo Form::close(); ?>

</body>

<script type="text/javascript">
   
    
    $("#venta_cliente_id").change(function () {
        buscaCliente();

    });

    $("#Agregar").click(function () {

        agregarPartida();

    });
    $("#condiciones").change(function () {
      var condiciones = $('#condiciones').val();  
      if(condiciones=="1"){
           $('#cajaCondiciones').hide();
      }else {
           $('#cajaCondiciones').show();
      }
   });
    $("#concepto_id").change(function () {
        var idConcepto = $('#concepto_id').val();
        if (idConcepto != '') {
            operacion = 'BUSCA_MOVIMIENTO';
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/funciones'; ?>",
                data: "operacion=" + operacion + "&idConcepto=" + idConcepto,
                success: function (html) {
                    var aux = html;
                    aux = aux.replace(/^\s+|\s+$/g, "");
                    $('#tipo_operacion').val(aux);
                    if (aux != "C") {
                        $('#cambio').hide();
                        $('#etiqCb').hide();
                        $('#p').hide();
                        //MUESTRA LOS CAMPOS COMPLEMENTARIOS PARA FORMA DE PAGO EN (BANCO)
                        $('#cajaDetalle').show();
                        operacion = 'BUSCA_BANCO';
                        $.ajax({
                            type: "POST",
                            url: "<?php echo PUBLIC_PATH . 'venta/funciones'; ?>",
                            data: "operacion=" + operacion,
                            success: function (html) {

                                $("#bancoI").html(html);
                            }
                        });


                    } else {
                        $('#cambio').show();
                        $('#etiqCb').show();
                        $('#p').show();
                        //OCULTA LOS CAMPOS COMPLEMENTARIOS PARA FORMA DE PAGO EN (BANCO)
                        $('#cajaDetalle').hide();
                       


                    }
                }
            });
        }

    });
    $("#importe_recibido").keyup(function(){
     validaMonto();
 }); 
 
    Number.prototype.formatMoney = function(decPlaces, thouSeparator, decSeparator) {
   var n = this,
   decPlaces = isNaN(decPlaces = Math.abs(decPlaces)) ? 2 : decPlaces,
   decSeparator = decSeparator === undefined ? "." : decSeparator,
   thouSeparator = thouSeparator === undefined ? "," : thouSeparator,
   sign = n < 0 ? "-" : "",
   i = parseInt(n = Math.abs(+n || 0).toFixed(decPlaces)) + "",
   j = (j = i.length) > 3 ? j % 3 : 0;
   return sign + (j ? i.substr(0, j) + thouSeparator : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + thouSeparator) + (decPlaces ? decSeparator + Math.abs(n - i).toFixed(decPlaces).slice(2) : "");
};
</script>  






