<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<br>
<div id="form_container" style="width:100%">
    <h1><a></a></h1>
</div>
  <div class="row">
     <div class="col-md-12">
       <h1><a></a></h1>
     </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>
            <span class="glyphicon glyphicon-th"></span>
            <span>Agregar Almacen</span>
         </strong>
        </div>
        <div class="panel-body">
            <?php echo Form::open("inventario/listadoAlmacen"); ?> 
        <div class="form-row">
            <div class="col-sm-7">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">   Clave:
                        </div>
                        
                        <?php echo Form::text('almacen.almacen', 'class="form-control" '); ?>
                       

                    </div>
                </div>
            </div> 

            <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">     Descripción:    
                        </div>
                        <?php echo Form::text('almacen.descripcion', 'class="form-control"  '); ?>
                    </div>
                </div>
            </div> 
     
            
            <div class="col-sm-7">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">     Tipo:    
                        </div>
                        <?php
                    $select = '0';
                
                $arregloEstado = array(''=>'Seleccione...','GENERAL'=>'General','PUNTO VENTA'=>'Punto de Venta');?>
                <?php echo Form::Select('almacen.tipo', $arregloEstado,'class="form-control"',$select); ?>
                    </div>
                </div>
            </div>
</div>
              
            <button type="submit" name="add_cat" class="btn btn-primary">Agregar Almacen</button>
        <?php echo Form::close(); ?>
        </div>
      </div>
    </div>
    <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong>
          <span class="glyphicon glyphicon-th"></span>
          <span>Listado de Almacenes</span>
       </strong>
      </div>
        <div id="form_container" style="width:100%">   
            <?php View::partial("formatoC",false,array('Encabezado'=>$encabezado,'Model'=>$result,'Campos'=>$campos));  ?>
</div>
    </div>
    </div>
   </div>

<script>
   function actualizar(){
       window.location.reload();
   }
</script> 