<?php
$d=count($destino);
$i=1;
$alma="";
foreach ($destino as $des){
    if($i<$d) $alma .=$des->descripcion.", ";
    else $alma .=$des->descripcion.".";
}
$d=count($ciclo);
$i=1;
$cicl="";
foreach ($ciclo as $cic){
    if($i<$d) $cicl .=$cic->ciclo.", ";
    else $cicl .=$cic->ciclo.".";
}
Load::lib('tcpdf');
class reporte extends TCPDF {

   

    public function Header() {
        
    }

    public function Footer() {
        /* establecemos el color del texto */
        $this->SetTextColor(0, 0, 0);
        $this->SetFont('helvetica', 'C', 7);

       
            $this->SetXY(10, 260);
            $this->MultiCell(110, 1, "1a. Cerrada de la Era No. 1 Barrio Quinta San Martín C.P. 29247 \n  Teléfonos 967 678 31 96 y 967 678 81 06 \n San Cristóbal de Las Casas, Chiapas.", 0, 'C');
            $this->SetXY(120, 260);
            $this->MultiCell(60, 1, "www.majomut.org \n mail: directivosmajomut@prodigy.net.mx \n  info@majomut.org", 0, 'C');
            $this->SetXY(182, 260);
            $this->SetFont('helvetica', 'C', 7);
            $this->MultiCell(30, 1, "" . $this->getAliasNumPage() . " / " . $this->getAliasNbPages() . " \n ", 0, 'C');
        
    }

}
$pdf = new reporte($orientation = 'P', $unit = 'mm', $format = 'Letter'); 

$pdf->SetAuthor('');
$pdf->SetTitle('Vale movimiento');
$pdf->SetSubject('');
//================================================================
//VARIABLES POR DECLARAR
$numEvento="PENDIENTE";
//================================================================
//================ SE GENERAN DATOS DE LA POLIZA  ==================
$logo='./img/logoReporte.png';

$titulo=' ';
$subtitulo1=''; 
$subtitulo2='';
$subtitulo3='DEL 01 AL  DE  DEL ';
$usuarioCaptura="";
$url='';


// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN,'' , 8));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', 7));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

//set margins
$pdf->SetMargins(10,10,10);//PDF_MARGIN_LEFT, '20', PDF_MARGIN_RIGHT
$pdf->SetHeaderMargin('10');//PDF_MARGIN_HEADER
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);



//set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

//set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

$pdf->setPageOrientation('P'); // PDF_PAGE_ORIENTATION---> 'L'= horizontal or 'P'=vertical
// ---------------------------------------------------------

// set default font subsetting mode
$pdf->setFontSubsetting(true);

// set default font subsetting mode
$pdf->setFontSubsetting(true);


    // reciboNomina($dir,$archivo);
  

// Set font
// dejavusans is a UTF-8 Unicode font, if you only need to
// print standard ASCII chars, you can use core fonts like
// helvetica or times to reduce file size.
//$pdf->SetFont('dejavusans', , 8, , true);

// Add a page
// This method has several options, check the source code documentation for more information.
$pdf->AddPage();
   
    ?>
<?php
 
    //set it to writable location, a place for temp generated PNG files


//ofcourse we need rights to create temp dir



//$longitud = count($datos);
// Set some content to print
$html="<style>
        .mitabla{
		font-size: 11px; 
		color: #333; 
	}
        .mitabla1{
		font-size: 9px; 
		color: #333; 
	}
        .mitabla2{
		font-size: 9px; 
		color: #333; 
                font:bold;
	}
        .resp{
        
        font-size:18px;
        font-family:Courier,monospace;
        font:bold;
     }
     .respTi{
        
        font-size:9px;
        font-family:Courier,monospace;
     }
        </style>";





$html .='
 <table class="mitabla" border="0" >
<thead>

<tr>
<th align="center" style="width: 20% ">

<img src="'.$logo.'" width="100" height="110"  />
</th>
<th align="left" style="width: 80%; font-weigth:18px;">

  <hr>
<font align="center" class="resp"><br>
UNION DE PRODUCTORES  ORGANICOS <br>
BENEFICIO MAJOMUT, S. DE P.R. DE R.L <br>
R.F.C.  UPO111114BJ7 <br>
</font>
 <hr>  
 

</th>

</tr>
<tr>
<th colspan="2">
<font align="center" class="resp">
<strong>VALE - TRASPASO  ENTRE ALMACENES</strong>
</font>
</th>
</tr>
</thead>
 <tbody>
          <tr>
          <td colspan="3">   
          

 

<br>
<br>
<table style="width: 100%" border="0" class="mitabla">   
    <tr >
        <td style="width: 20%" border="0" ><strong>Organización: </strong>      </td>
        <td style="width: 15%" border="0" >Majomut           </td>
        <td style="width: 10%" border="0" >             </td>
        <td style="width: 10%" border="0" >             </td>
        <td style="width: 15%" border="0" > <strong>Fecha:</strong>            </td>
        <td style="width: 25%" border="0" >'.$datosCompra->fecha_salida.'            </td>
    </tr>
       <tr>
        <td  ><strong>Num. Vale:      </strong>   </td>
        <td  >'.$datosCompra->documento.'  </td>  
        <td  >             </td>  
        <td  >             </td>  
        <td  ><strong>Ciclo:</strong>    </td>  
        <td  >'.$cicl.'            </td>  
    </tr>
    
      
 </table>

 </td>
</tr>

<tr>
<td colspan="3">

</td>
</tr>

<tr>
<td colspan="3">
<table style="width: 100%" border="1" class="mitabla1" cellpadding="3">
<tr align="center" bgcolor="#CCCCCC">
<td style="width: 15%">Movimiento </td>
<td style="width: 15%">Almacen </td>
<td style="width: 10%">Lote </td>
<td style="width: 25%">Tipo Preparacion </td>
<td style="width: 25%">Presentación </td>
<td style="width: 10%">Cantidad / Unidad </td>

</tr>';
$i=1;
$c1=0;$c2=0;$c3=0;$c4=0;
foreach ($detalleCompra as $datos){
    $cantidad= $datos->cantidad;
     $producto=new producto();
 $producto=$producto->find_first("id='$datos->producto_id'");
 if($producto->medida_id=="1"){
 $unidadEmpaque=$datos->unidad;
 $pesoEmpaque=$producto->peso_empaque;
 if($unidadEmpaque>0){
 $paquete= $cantidad/$unidadEmpaque;
 $residuo= $cantidad%$unidadEmpaque;
 $paquete=floor($paquete);
 if($residuo > $pesoEmpaque){$paquete++; $pesoPaquete=$paquete;  }
 else {$pesoPaquete=$paquete;}
 $cantidadA=$cantidad-($pesoPaquete);
 }else{
     $paquete=0;
     $cantidadA=$cantidad;
 }
 
 }
 $c1 +=$paquete;
 $c2 +=$cantidad;
 $c3 +=$paquete;
 $c4 +=$cantidadA;
$html .=' <tr align="center">
<td style="width: 15%">'.$datos->movimiento.' </td>
<td style="width: 15%" >'.$datos->almacen.' </td>
<td style="width: 10%" >'.$datos->codigo.'</td>
<td style="width: 25%" >'.$datos->descripcion.' '.$datos->preparacion.'</td>
<td style="width: 25%" >'.$datos->calidad.'</td>
<td style="width: 10%" >'.$datos->cantidad.' - '.$datos->medida.'</td>

</tr>'; 
$i++;
}

if($i<5){
for($j=$i;$j<=5;$j++){
 $html .=' <tr align="center">
<td style="width: 15%;height: 19px;"></td>
<td style="width: 15%"></td>
<td style="width: 10%"></td>
<td style="width: 25%"></td>
<td style="width: 25%"></td>
<td style="width: 10%"></td>

</tr>';    
}    
}
$html .=' <tr align="center" bgcolor="#CCCCCC">

<td style="width: 15%"></td>
<td style="width: 15%"></td>
<td style="width: 10%"></td>
<td style="width: 25%"></td>
<td style="width: 25%"></td>
<td style="width: 10%"></td>

</tr>'; 
$html .='</table> </td></tr>';

$html .=' <tr><td colspan="3"> <table style="width: 100%" border="0" class="mitabla">
<tr>
<td> </td>
</tr>
</table>
 
<table style="width: 100%" border="0" class="mitabla">
<tr class="respTi">
<td style="width: 14%" border="0"><strong>Observaciones:</strong></td>
<td border="1" style="width: 86%"> '.$datosCompra->observacion.' </td>
</tr>
</table> 

    </td>   </tr>';    
 
 $html .='<tr><td colspan="3"><table style="width: 100%" border="0" class="mitabla1">
<tr>
<td> </td>
</tr>
</table>
<br><br>
 <table style="width: 100%" border="0" class="mitabla2">
<tr align="center">
<td style="width: 33%"> CAPTURO <BR>
<BR>
<BR>
<BR>
<BR>
__________________________________
<BR>
'.$datosCompra->capturo.'  <BR>
    
</td>
<td style="width: 33%"> RECIBIO <BR>
<BR>
<BR>
<BR>
<BR>
__________________________________
<BR>
'.$datosCompra->recibio.'  <BR>
  
</td>
<td > VALIDO <BR>
<BR>
<BR>
<BR>
<BR>
__________________________________
<BR>
'.$datosCompra->valido.'  <BR>
   
</td>
</tr>
 
</table> 
</td>
</tr> 
</tbody>
</table>
      ';    
   
  //echo $html
//print_r($datos);
ob_end_clean(); 
// Print text using writeHTMLCell()
$pdf->writeHTML($html, true, false, true, false, '');

// ---------------------------------------------------------

// Close and output PDF document
// This method has several options, check the source code documentation for more information.
 //$pdf->Output('reporte.pdf', 'I');


   ob_end_clean();  

 $pdf->Output('valeMovimiento.pdf', 'I');

?>

