<?php View::content(); ?>
<div id="form_container" style="width:100%">
    <h1><a></a></h1>
    <br/>
</div>

   <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>
            <span class="glyphicon glyphicon-th"></span>
            <span>Agregar Costo de Envio</span>
         </strong>
        </div>
        <div class="panel-body">
          <?php echo Form::open("envios/editarEnvio/".$costo->id); ?>
            <?php echo Form::hidden( 'costo.id', 'class="form-control"'); ?>
            <div class="form-group">
                Empresa envio <br> 
          <?php   echo Form::dbSelect("costo.empresa_id", "nombre", array("empresa", "listar"), 'Seleccione..', 'class="form-control" required '); ?>
        </div>
            <div class="form-group">
                Codigo <br> 
             <?php echo Form::text('costo.codigo', ' class="form-control" required '); ?>
        </div>
              <div class="form-group">
                Numero kilos <br> 
             <?php echo Form::number('costo.kilos', ' class="form-control" required  '); ?>
        </div>
              <div class="form-group">
                Costo <br> 
           <?php echo Form::number('costo.costo', ' class="form-control" required '); ?>
        </div>
              
              
          <?php $url ="'" .  PUBLIC_PATH . "envios/index'"; ?>  
            <div class="col-sm-6">
                <div class="form-group">
                   <?php echo Form::button("Cancelar", 'class="btn btn-danger" onclick="window.location = ' . $url . '" '); ?>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                   <button type="submit" name="add_cat" class="btn btn-success">Actualizar</button>  
                </div>
            </div>  
        <?php echo Form::close(); ?>
        </div>
      </div>
    </div>
    
   </div>
  

