<?php View::content(); ?>
<div id="form_container" style="width:100%">
    <h1><a></a></h1>
    <br/>
</div>

   <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>
            <span class="glyphicon glyphicon-th"></span>
            <span>Agregar Costo de Envio</span>
         </strong>
        </div>
        <div class="panel-body">
          <?php echo Form::open("envios/index/"); ?>
            <div class="form-group">
                Empresa envio <br> 
          <?php   echo Form::dbSelect("costo.empresa_id", "nombre", array("empresa", "listar"), 'Seleccione..', 'class="form-control" required '); ?>
        </div>
            <div class="form-group">
                Codigo <br> 
             <?php echo Form::text('costo.codigo', ' class="form-control" required '); ?>
        </div>
              <div class="form-group">
                Numero kilos <br> 
             <?php echo Form::number('costo.kilos', ' class="form-control" required  '); ?>
        </div>
              <div class="form-group">
                Costo <br> 
           <?php echo Form::number('costo.costo', ' class="form-control" required '); ?>
        </div>
              
              
            <button type="submit" name="add_cat" class="btn btn-success">Agregar Costo</button>
        <?php echo Form::close(); ?>
        </div>
      </div>
    </div>
    <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong>
          <span class="glyphicon glyphicon-th"></span>
          <span>Lista de Costos de Envios</span>
       </strong>
      </div>
        <div id="form_container" style="width:100%">   
<?php View::partial("formatoC",false,array('Encabezado'=>$encabezado,'Model'=>$result,'Campos'=>$campos,'ctrleditar'=>"editarEnvio/",'ctrleliminar'=>"eliminarEnvio/"));  ?>
</div>
    </div>
    </div>
   </div>
  

