
<?php
View::content();
$anio = date('Y') - 10;
$total=0;
?>
<?php $url = "'" . PUBLIC_PATH . "'"; ?>
<body id="cuerpo_principal">
    <div id="form_container" style="width:100%;" >
<h1><a></a></h1>
    <div id="titulo_superior"> 
        <div id="texto_superior"  >
                 <?php echo "Concentrado de Ventas" ?> 
            </div>
            <div style="text-align:right;margin: 0 0; width:49%; float: left; ">
             <div class='btn'>
                    <?php echo Html::img('inicio.png','cancel','style="text-align:center;width:65px;  padding:5px;"  onclick="window.location = ' . $url . '" ');?>
                </div>  
               
            </div>
    </div>  
<?php echo Form::open("venta/concentradoVentas"); ?>  
        <table width="100%" border="0">
            <tr align="center">
                <td>
                    <table width="100%" border="0">
                        <tr style="width:100%;">
                             <td><fieldset style="padding: 15px; height: 100%">
                                   
                                    <table style="width:100%;" border="0">
                                        <tr align="center">
                                            <td style="width:50%;" >                
                                                <div class="tres_a">

<?php echo Form::date('fecha_inicial', 'class="element text" required', date('Y-m-d')); ?>
                                                    <br> <label> Periodo Inicial</label>       
                                                </div>
                                            </td>
                                            <td><div class="tres_b">

<?php echo Form::date('fecha_final', 'class="element text" required ', date('Y-m-d')); ?>
                                                    <br>  <label> Periodo Final</label>
                                                </div>

                                            </td>
                                            

                                        </tr>
                                    </table>
                                </fieldset></td>
                            
                             <td>
                             
                             <fieldset style="padding: 15px; height: 100px">
                                    
                                    <table width="100%" border="0">
                                        <tr>
                                            <td>Lote</td>
                                            <td><?php echo Form::dbSelect("codigoS","codigo",array("lote","listar"),' ','type="text"  class="element text" style="width:325px"');?></td>
                                                <td><?php echo form::submit("MOSTRAR", 'class="CSSButton" '); ?></td>
                                        
                                        </tr>
                                    </table>
                                </fieldset>
                             </td>
                        </tr>
                       
                        <tr>
                            <td  colspan="3"> 
                                 <fieldset style="padding: 15px; width: 100%;">
                    <legend><b>Datos de la Consulta </b></legend>
     
    <table class=" table table-bordered" >

        <tr  bgcolor="#00984f" align="center">
            <th width="5%">#</th>
            <th width="9%">Fecha Venta</th>
            <th width="8%" >Clave</th>
            <th width="20%" >Producto</th>
            <th width="9%" >Presentacion</th>
            <th width="6%" >Pienza(s)</th>
              <th width="10%" >Calidad</th>
              <th width="10%" >Almacen</th>
            <th width="10%" >Lote</th>
            
            <th width="10%" >Cantidad</th> 
            <th width="10%" >Importe</th>    
        </tr>
    </table>
       <div id="contenidoCobrar" style="overflow: scroll; height: 400px">  
           <table width="100%" class=" table table-bordered" > 
           <?php 
                            $color="#0174DF";
                            $i=0;
                            $cantidad=0;
                            $total=0;
                            if(isset($resultado))
                            foreach ($resultado as $datos){
                             $i++; 
                             if($color=="#0174DF")
        {
$color="#FFFFFF";
}
else
{
$color="#FFFFFF";
} 
        (($datos->subtotal<1)? $datos->subtotal=0:'');
        (($datos->iva<1)? $datos->iva=0:'');
        (($datos->monto<1)? $datos->monto=0:'');
        ?>
            <tr valign="center" style="background-color:<?php echo $color ?>">      
            <td width="5%"> <?php echo $i; ?> </td>
            <td width="9%"> <?php echo "  ".$datos->fecha_recepcion; ?> </td>
            <td width="8%"> <?php echo "  ".$datos->clave; ?> </td>
            <td width="20%"> <?php echo "  ".$datos->descripcion; ?> </td>
            <td width="9%"> <?php if($datos->presentacion_venta=='0.500') echo "1/2 Kg"; else if($datos->presentacion_venta=='0.250') echo "1/4 Kg"; ?> </td>
            <td width="6%"> <?php if(($datos->presentacion_venta!='1.000') && ($datos->presentacion_venta >0) ) echo floatval ($datos->cantidad) / floatval ($datos->presentacion_venta) ; ?> </td>
            <td width="10%"> <?php echo "  ".$datos->preparacion; ?> </td>
            
            <td width="10%" align="right"><?php echo $datos->origen; ?> </td>
             <td width="10%" align="right"><?php echo $datos->lote; ?> </td>
            <td width="10%" align="right"><?php echo "  ".number_format($datos->cantidad,2); ?> </td>
            <td width="10%" align="right"><?php echo "  ".number_format($datos->total,2); ?> </td>
             </tr>
       
                           <?php 
                            $cantidad=$cantidad+$datos->cantidad;
                           $total = $total + $datos->total;
                           
                          
}    ?>  
             
		</table> </div>
                    <table  width="100%" border="0"  class="arqueo">
                    <tr height="50px">
              <td colspan="4" width="79%" align="right"> Total :  </td>
              <td width="10%" align="right">  <?php echo "  ".number_format($cantidad,2); ?> </td>
              <td width="10%" align="right">  <?php echo "  ".number_format($total,2); ?> </td>
            <td width="1%" align="right">  </td> 
             </tr>
		</table>
     </fieldset>
                                
                               </td> 
                            
                        </tr>
                        <tr>
                            <td colspan="3" height="50px"></td>
                        </tr>
                        
                    </table>
                </td>
            </tr>
        </table>
<?php echo Form::hidden('codigo', 'class="element text" required ' ); ?>
<?php echo Form::close(); ?>
    </div>


</body>               

<?php ?>

<script type="text/javascript">
    $(document).ready(function() {
    $("#codigoS").change(function() {
       
        texto=$('#codigoS option:selected').html();
        $("#codigo").val(texto);
    });
});
    </script>