<script>
    function imprime_lista()
    {
        var operacion = 'MOSTRAR_LISTA'
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "operacion=" + operacion,
            success: function (html) {
                $("#resultado").html(html);
                $("#dsubtotal").val($("#iSubtotal").val());
                $("#dimpuesto").val($("#iImpuesto").val());
                $("#dtotal").val($("#iTotal").val());
            }
        });

    }
    function buscaDetalle()
    {
        var productoId = $('#cotizacion_producto_id').val();
        var operacion = 'MOSTRAR_DETALLE'
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'inventario/libreriaInventario/'; ?>",
            data: "productoId=" + productoId + "&operacion=" + operacion,
            success: function (html) {
                html = "lote";
                html = html.replace(/^\s+|\s+$/g, "");
                $('#opcion').val(html);
                if (html == "lote") {
                    $('#loteProducto').show();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').hide();
                    $('#serie').val('');
                    $('#numInventario').val('');

                } else if (html == "serie") {
                    $('#loteProducto').hide();
                    $('#serieProducto').show();
                    $('#inventarioProducto').hide();
                    $('#numInventario').val('');
                    $('#lote').val('');
                } else if (html == "loteInventario") {
                    $('#loteProducto').show();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').show();
                    $('#serie').val('');
                } else if (html == "serieInventario") {
                    $('#loteProducto').hide();
                    $('#serieProducto').show();
                    $('#inventarioProducto').show();
                    $('#lote').val('');
                } else if (html == "soloInventario") {
                    $('#loteProducto').hide();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').show();
                    $('#lote').val('');
                    $('#serie').val('');
                } else {
                    $('#inventarioProducto').hide();
                    $('#loteProducto').hide();
                    $('#serieProducto').hide();
                    $('#serie').val('');
                    $('#lote').val('');
                    $('#numInventario').val('');

                }
                //  $("#detalleProducto").html(html);
            }
        });

    }
    function buscaUnidadPrecio() {
        var productoId = $('#cotizacion_producto_id').val();

        var operacion = "BUSCA_UNIDADPRECIO";
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "productoId=" + productoId + "&operacion=" + operacion,
            success: function (html) {
               
                separador = ","
                cadena=html.split(separador)
                $("#etiqueta").html(cadena[0]);
                var valor=cadena[1];
                 $("#cotizacion_precio").val(valor);
                  
            }
        });
    }
    function buscaCliente() {
        var clienteId = $('#cotizacion_cliente_id').val();
        if (clienteId > 0) {
            var operacion = "BUSCA_CLIENTE_C";
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                data: "clienteId=" + clienteId + "&operacion=" + operacion,
                success: function (html) {
                    $("#cliente").html(html);
                }
            });
        }
    }
    function agregarPartida()
    {

        var operacion = 'AGREGAR_PARTIDA';
        var cantidad = $('#cotizacion_cantidad').val();
        var productoId = $('#cotizacion_producto_id').val();
        var precio = $('#cotizacion_precio').val();
        var serie = "";
        var lote = $('#lote').val();
        var opcion = 'lote';
        var mens = "";
        var re = /,/g;
        cantidad = cantidad.replace(re, "");

        if (cantidad == "") {
            mens += "\n- Inserte una cantidad valida";
        }
        if (productoId == "") {
            mens += "\n- Elija un producto";
        }
        


        if (mens != "") {
            alert('Verifique los siguientes campos:\n' + mens);

        } else
        {
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                data: 'operacion=' + operacion + '&cantidad=' + cantidad + "&productoId=" + productoId + "&precio=" + precio + "&lote=" + lote + "&serie=" + serie + "&opcion=" + opcion,
                success: function (html) {

                    html = html.replace(/^\s+|\s+$/g, "");
                    if (html == 'Si') {
                        alert('Esta partida ya existe.......!');
                    } else {

                        imprime_lista();
                    }
                }
            });
        }
    }

    function quitar_partida(linea)
    {

        var operacion = 'QUITAR_PARTIDA'
        var linea = linea;

        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "operacion=" + operacion + "&linea=" + linea,
            success: function (html) {
                imprime_lista();
            }
        });


    }
</script>    
<?php View::content(); ?>
<body id="cuerpo_principal">

    <div id="form_container" style="width:100%;" >
        <br>
        <h1><a></a></h1>
        <div id="titulo_superior"> 
            <div id="texto_superior"  >
                <?php echo "Cotización" ?> 
            </div>
            <div style="text-align:right;margin: 0 0; width:49%; float: left; ">
                <div class='btn'>
                    <?php
                    echo Html::linkAction('listadoCotizacion', Html::img('verLista.png', 'cancel', 'style="text-align:center;width:90px;  padding:2px;"'), '');
                    ?>
                </div>
            </div>
        </div>
        <?php echo Form::open("venta/" . $accion); ?>
        <?php echo Form::hidden("cotizacion.id"); ?>



        <div id="margen" >
            <div class="form-row">


                <?php echo Form::hidden('cotizacion.tipo_documento', 'maxlength="20" required class="form-control"   ', "COTIZACION"); ?>

                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Documento:    
                            </div>
                            <?php echo Form::text('cotizacion.documento', ' readonly="readonly" maxlength="20" required class="form-control"   ', $num); ?>
                        </div>
                    </div> 
                </div>

                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Fecha:    
                            </div>
                            <?php echo form::date('cotizacion.fecha_documento', 'placeholder="dd-mm-aa" required class="form-control"', date('Y-m-d')); ?>
                        </div>
                    </div> 
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">    Cliente:    
                            </div>
                            <?php echo Form::dbSelect("cotizacion.cliente_id", "nombrecompleto", array("cliente", "listar"), 'Seleccione..', ' class="form-control" '); ?>
                        </div>
                    </div> 
                </div>


            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">Datos Cliente </div>
                <div class="panel-body">
                    <div id="cliente">
                        <table width="100%" border="0">
                            <tr>
                                <td width="104"><label> Cliente:</label></td>
                                <td width="551"><input name="nombre" id="nombre" type="text" size="40"  class="letra" readonly="readonly"/></td>
                            </tr>
                            <tr>
                                <td><label> Direccion:</label></td>
                                <td><input type="text" name="direccion" id="direccion" size="50"  class="letra" readonly="readonly"/></td>
                            </tr>
                            <tr>
                                <td><label> Telefono:</label></td>
                                <td><input name="rfc" id="rfc" type="text" size="15"   class="letra" readonly="readonly"/></td> 
                            </tr>
                            <tr>
                                <td><label> Email:</label></td>
                                <td><input name="rfc" id="rfc" type="text" size="25"   class="letra" readonly="readonly"/></td> 
                            </tr>
                            <tr>
                                <td><label> Organizacion:</label></td>
                                <td><input name="rfc" id="rfc" type="text" size="55"   class="letra" readonly="readonly"/></td> 
                            </tr>
                        </table>
                    </div>   
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">Datos Producto </div>
                <div class="panel-body">
                    <div class="form-row">
                        <div class="col-md-3 mb-3">
                            <label for="validationCustomUsername">Producto</label>
                            <div class="input-group">

                                <?php echo Form::dbSelect("cotizacion.producto_id", "descripcion", array("producto", "listarEntrada"), 'Seleccione..', ' class="form-control"'); ?>

                            </div>
                        </div> 
                        <div class="col-md-2 ">
                            <label >cantidad</label>
                            <div class="input-group">

                                <?php echo Form::number('cotizacion.cantidad', ' class="form-control"  ','0'); ?>

                            </div>
                        </div> 


                        <div class="col-md-2 ">
                            <label >.</label>
                            <div class="input-group">
                                <div  id="etiqueta" >
                                   
                                </div>
                            </div>
                        </div> 

                        <div class="col-md-3 ">
                            <label >Precio</label>
                            <div class="input-group">
                               
                                  <?php echo Form::text('cotizacion.precio', '  class="form-control"  ','0'); ?>
                                
                            </div>
                        </div> 
                        <div class="col-md-2 ">
                            <label >.</label>
                            <div class="input-group">
                                <?php echo Form::button("Agregar", "id='Agregar' style='width:98%;' class='btn-success btn' ") ?>
                            </div>
                        </div> 

                    </div>      


                    <div id="resultado" style="height: 200px; border-bottom:1px;  border-bottom-color:#000; "> <?php print"<script> imprime_lista() </script>"; ?></div>
                    </br>
                    <table width="100%" border="0">
                        <tr>
                            <td style="width: 80%;text-align: right;"> SubTotal $ </td>
                            <td style="width: 1%;"></td>
                            <td><?php echo Form::text('dsubtotal', '  class="form-control"  style="text-align:right;" '); ?> </td>
                        </tr>
                        <tr>
                            <td style="width: 80%;text-align: right;"> Impuesto $ </td>
                            <td style="width: 1%;"></td>
                            <td><?php echo Form::text('dimpuesto', '  class="form-control" style="text-align:right;"  '); ?> </td>
                        </tr>
                        <tr>
                            <td style="width: 80%;text-align: right;"> Total $ </td>
                            <td style="width: 1%;"></td>
                            <td><?php echo Form::text('dtotal', '  class="form-control" style="text-align:right;"  '); ?> </td>
                        </tr>
                    </table>
                    <br/>

                    <table style="width: 100%" border="0">

                        <tr >
                            <td>Observaciones:</td>
                            <td><?php echo Form::textarea('cotizacion.observacion', '  class="form-control"  '); ?></td>

                        </tr>
                    </table>
                    <br>
            <div class="col-sm-4">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon">       Costo Envio:    
                                </div>
                                <?php echo Form::dbSelect("cotizacion.costo_envio", 'costo', array('costoEnvio', 'datos', 0), '- Seleccione -', " class='form-control' "); ?>
                                 </div>
                        </div> 
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon">       Capturo:    
                                </div>
                                <?php echo Form::text('cotizacion.capturo', ' required class="form-control"   '); ?>
                            </div>
                        </div> 
                    </div>
                   
                </div>
            </div>  
            <?php $url = "'" . PUBLIC_PATH . "venta/listadoCotizacion'"; ?>
            <table width="100%">
                <tr align="center">
                    <td width="33%">     
                        <?php echo Form::button("Cancelar", 'class="btn btn-lg btn-danger" onclick="window.location = ' . $url . '" '); ?>
                    </td>
                    <td>

                    </td>
                    <td width="33%">
                        <?php echo Form::submit((($accion == 'crearCotizacion') ? 'Guardar' : 'Actualizar'), 'type="submit" class="btn btn-lg btn-primary"'); ?>       
                    </td>
                </tr>
            </table>

        </div> 
    </div>
    </br>
    <?php echo Form::close(); ?>

</body>

<script type="text/javascript">
    $("#cotizacion_producto_id").change(function () {
        buscaUnidadPrecio()
    });
    $("#cotizacion_cliente_id").change(function () {
        buscaCliente();

    });

    $("#Agregar").click(function () {

        agregarPartida();

    });
</script>  






