<script type="text/javascript">
   
    
    function buscaCliente() {
        var clienteId = $('#anticipo_cliente_id').val();
        if (clienteId > 0) {
            var operacion = "BUSCA_CLIENTE_AN";
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                data: "clienteId=" + clienteId + "&operacion=" + operacion,
                success: function (html) {
                    $("#cliente").html(html);
                }
            });
        }
    }
    
</script>    
<?php View::content(); ?>
<body id="cuerpo_principal">

    <div id="form_container" style="width:100%;" >
        <br>
        <h1><a></a></h1>
        <div id="titulo_superior"> 
            <div id="texto_superior"  >
                <?php echo "REGISTRO DE ANTICIPO" ?> 
            </div>
            <div style="text-align:right;margin: 0 0; width:49%; float: left; ">
                <div class='btn'>
                    <?php
                    echo Html::linkAction('listadoAnticipo', Html::img('verLista.png', 'cancel', 'style="text-align:center;width:90px;  padding:2px;"'), '');
                    ?>
                </div>
            </div>
        </div>
        <?php echo Form::open("venta/" . $accion); ?>
        <?php echo Form::hidden("anticipo.id"); ?>



        <div id="margen" >
            <div class="form-row">


                <?php echo Form::hidden('anticipo.tipo_documento', 'maxlength="20" required class="form-control"   ', "VENTA"); ?>

                
               <div class="col-sm-8">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">    Cliente:    
                            </div>
<?php echo Form::dbSelect("anticipo.cliente_id", "nombrecompleto", array("cliente", "listar"), 'Seleccione..', ' class="form-control" required '); ?>
                        </div>
                    </div> 
                </div>

                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Fecha:    
                            </div>
<?php echo form::text('anticipo.fecha_documento', 'placeholder="dd-mm-aa" required class="form-control"', date('d-m-Y')); ?>
                        </div>
                    </div> 
                </div>
                


            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">Datos Cliente </div>
                <div class="panel-body">
                    <div id="cliente">
                        <table width="100%" border="0">
                            <tr>
                                <td width="104"><label> Nombre:</label></td>
                                <td width="551"><input name="anticipo.nombre" id="anticipo.nombre" type="text" size="100"  class='form-control' readonly="readonly"/></td>
                            </tr>
                            <tr>
                                <td><label> Direccion:</label></td>
                                <td><input type="text" name="anticipo.direccion" id="anticipo.direccion" size="100"  class='form-control' readonly="readonly"/></td>
                            </tr>
                            <tr>
                                <td><label> RFC:</label></td>
                                <td><input name="anticipo.rfc" id="anticipo.rfc" type="text" size="15"   class="letra" readonly="readonly"/></td> 
                            </tr>
                        </table>
                    </div>   
                </div>
            </div>
            
<?php $ar2 = array('Contado', 'Credito'); ?>
            <fieldset style="padding: 15px;">
                <legend><b>Datos del Anticipo :</b></legend> 
               

                <div class="col-sm-9">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Forma de pago:
                            </div>
<?php echo Form::dbSelect("anticipo.concepto_id", 'concepto', array('conceptos', 'listar', 0), '- Seleccione -', " class='form-control' required"); ?>
                        </div>
                    </div> 
                </div>

                    <div id="cajaDetalle" style="display: none">
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Referencia:    
                            </div>
<?php echo Form::text('anticipo.referencia', 'maxlength="30" class="form-control"  '); ?>
                        </div>
                    </div> 
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Fecha de documento:    
                            </div>
<?php echo Form::date('anticipo.fecha_referencia', 'type="text" class="form-control" placeholder="dd-mm-aa" '); ?> 
                        </div>
                    </div> 
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Cuenta Bancaria:    
                            </div>
<?php echo Form::dbSelect("anticipo.cuenta_id", 'cuenta', array('bancosCuentas', 'listarCuentasBancos', 0), '- Seleccione -', " class='form-control '  "); ?>
                        </div>
                    </div> 
                </div>
                    </div>
                    
                <div class="col-sm-12">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Uso del CFDI :    
                            </div>
<?php echo Form::dbSelect("anticipo.uso_id", 'descripcion', array('usoCfdi', 'listar', 0), '- Seleccione -', " class='form-control input-sm' required  "); ?>
                        </div>
                    </div> 
                </div>
                <table width="100%" border='0'>



                    <tr>
                        <td colspan="2" rowspan="3" width="60%">
                            <label class="description"> Observaciones </label>  
<?php echo Form::textarea('anticipo.observacion', '  class="form-control"  '); ?>
                        </td> 
                        <td width="20%" style="text-align: right">Importe  $</td>
                        <td width="20%" valign="middle">
                            <div style="margin-top: 4px" class="input-group">

<?php echo Form::text('anticipo.importe', 'maxlength="20" class="form-control" size="10" style="text-align:right;"', 0); ?>

                            </div>
                        </td>
                    </tr>

                    
                </table>    
        </div>

    </fieldset>


<?php $url = "'" . PUBLIC_PATH . "anticipo/listadoAnticipo'"; ?>
    <table width="100%">
        <tr align="center">
            <td width="33%">     
<?php echo Form::button("Cancelar", 'class="btn btn-lg btn-danger" onclick="window.location = ' . $url . '" '); ?>
            </td>
            <td>

            </td>
            <td width="33%">
<?php echo Form::submit((($accion == 'crearAnticipo') ? 'Guardar' : 'Actualizar'), 'type="submit" class="btn btn-lg btn-primary"'); ?>       
            </td>
        </tr>
    </table>

</div> 
</div>
</br>
<?php echo Form::close(); ?>

</body>

<script type="text/javascript">
   
    
    $("#anticipo_cliente_id").change(function () {
        buscaCliente();

    });

   
    $("#anticipo_concepto_id").change(function () {
        var idConcepto = $('#anticipo_concepto_id').val();
        
        if (idConcepto != '') {
            operacion = 'BUSCA_MOVIMIENTO';
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/funciones'; ?>",
                data: "operacion=" + operacion + "&idConcepto=" + idConcepto,
                success: function (html) {
                    var aux = html;
                    aux = aux.replace(/^\s+|\s+$/g, "");
                    $('#tipo_operacion').val(aux);
                    if (aux != "C") {
                        $('#cambio').hide();
                        $('#etiqCb').hide();
                        $('#p').hide();
                        //MUESTRA LOS CAMPOS COMPLEMENTARIOS PARA FORMA DE PAGO EN (BANCO)
                        $('#cajaDetalle').show();
                        operacion = 'BUSCA_BANCO';
                        $.ajax({
                            type: "POST",
                            url: "<?php echo PUBLIC_PATH . 'venta/funciones'; ?>",
                            data: "operacion=" + operacion,
                            success: function (html) {

                                $("#bancoI").html(html);
                            }
                        });


                    } else {
                        $('#cambio').show();
                        $('#etiqCb').show();
                        $('#p').show();
                        //OCULTA LOS CAMPOS COMPLEMENTARIOS PARA FORMA DE PAGO EN (BANCO)
                        $('#cajaDetalle').hide();
                       


                    }
                }
            });
        }

    });
    $("#importe_recibido").keyup(function(){
     validaMonto();
 }); 
 
    Number.prototype.formatMoney = function(decPlaces, thouSeparator, decSeparator) {
   var n = this,
   decPlaces = isNaN(decPlaces = Math.abs(decPlaces)) ? 2 : decPlaces,
   decSeparator = decSeparator === undefined ? "." : decSeparator,
   thouSeparator = thouSeparator === undefined ? "," : thouSeparator,
   sign = n < 0 ? "-" : "",
   i = parseInt(n = Math.abs(+n || 0).toFixed(decPlaces)) + "",
   j = (j = i.length) > 3 ? j % 3 : 0;
   return sign + (j ? i.substr(0, j) + thouSeparator : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + thouSeparator) + (decPlaces ? decSeparator + Math.abs(n - i).toFixed(decPlaces).slice(2) : "");
};
</script>  






