<script type="text/javascript">
   function imprime_lista()
    {
        var operacion = 'MOSTRAR_LISTA_ANTICIPO'
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "operacion=" + operacion,
            success: function (html) {
                $("#resultado").html(html);
                $("#dsubtotal").val($("#iSubtotal").val());
                $("#dimpuesto").val($("#iImpuesto").val());
                $("#dtotal").val($("#iTotal").val());
                
            }
        });

    }
    
    function buscaCliente() {
        var clienteId = $('#anticipo_cliente_id').val();
        if (clienteId > 0) {
            var operacion = "BUSCA_CLIENTE_AN";
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                data: "clienteId=" + clienteId + "&operacion=" + operacion,
                success: function (html) {
                    $("#cliente").html(html);
                }
            });
        }
    }
    function buscaProducto() {
        var almacenId = $('#anticipo_almacen_id').val();

        var operacion = "BUSCA_PRODUCTO";
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "almacenId=" + almacenId + "&operacion=" + operacion,
            success: function (html) {
                $("#productoEs").html(html);
            }
        });
    }
    function buscaUnidadPrecio() {
        var productoId = $('#venta_producto_id').val();

        var operacion = "BUSCA_UNIDADPRECIO";
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "productoId=" + productoId + "&operacion=" + operacion,
            success: function (html) {

                separador = ","
                cadena = html.split(separador)
                $("#etiqueta").html(cadena[0]);
                var valor = cadena[1];
                $("#venta_precio").val(valor);
                 buscaLote();
        buscaDetalle();
         buscaPresentacion();
            }
        });
    }
      function buscaDetalle()
    {
        var productoId = $('#venta_producto_id').val();
        var operacion = 'MOSTRAR_DETALLE'
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'inventario/libreriaInventario/'; ?>",
            data: "productoId=" + productoId + "&operacion=" + operacion,
            success: function (html) {
                html = "lote";
                html = html.replace(/^\s+|\s+$/g, "");
                $('#opcion').val(html);
                if (html == "lote") {
                    $('#loteProducto').show();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').hide();
                    $('#serie').val('');
                    $('#numInventario').val('');

                } else if (html == "serie") {
                    $('#loteProducto').hide();
                    $('#serieProducto').show();
                    $('#inventarioProducto').hide();
                    $('#numInventario').val('');
                    $('#lote').val('');
                } else if (html == "loteInventario") {
                    $('#loteProducto').show();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').show();
                    $('#serie').val('');
                } else if (html == "serieInventario") {
                    $('#loteProducto').hide();
                    $('#serieProducto').show();
                    $('#inventarioProducto').show();
                    $('#lote').val('');
                } else if (html == "soloInventario") {
                    $('#loteProducto').hide();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').show();
                    $('#lote').val('');
                    $('#serie').val('');
                } else {
                    $('#inventarioProducto').hide();
                    $('#loteProducto').hide();
                    $('#serieProducto').hide();
                    $('#serie').val('');
                    $('#lote').val('');
                    $('#numInventario').val('');

                }
                //  $("#detalleProducto").html(html);
            }
        });

    }
    function buscaPresentacion() {
        var productoId = $('#venta_producto_id').val();
            var operacion = "TIPO_PRESENTACION";
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                data: "productoId=" + productoId + "&operacion=" + operacion,
                success: function (html) {
                    $("#tipoVenta").html(html);
                }
            });
        
    }
    function buscaLote() {
        var almacenId = $('#anticipo_almacen_id').val();
        var productoId = $('#venta_producto_id').val();
        var operacion = "BUSCA_LOTE_PA";
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "almacenId=" + almacenId + "&productoId=" + productoId + "&operacion=" + operacion,
            success: function (html) {
                $("#loteProducto").html(html);
            }
        });
    }
    
    function buscaExistencia() {
        var lote = $('#lote').val();
        var operacion = "BUSCA_EXISTENCIA_PA";
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "lote=" + lote  + "&operacion=" + operacion,
            success: function (html) {
                $("#existencia").val(html);
            }
        });
    }
    function agregarPartida()
    {
trans=0;
        var operacion = 'AGREGAR_PARTIDA_ANTICIPO';
        var cantidad = $('#venta_cantidad').val();
        var productoId = $('#venta_producto_id').val();
        var precio = $('#venta_precio').val();
        var almacenId = $('#anticipo_almacen_id').val();
        var presentacionVe=$('#presentacionVenta').val();
        if(presentacionVe=='T') var presentacion = $('#presentacionT').val();
        else {
            var presentacion = $('#presentacionV').val();
            trans=presentacion;
         
        }
        var existencia 	=	$('#existencia').val();
        var serie = "";
        var lote = $('#lote').val();
        var opcion = 'lote';
        var mens = "";
        var re = /,/g;
        cantidad = cantidad.replace(re, "");
if (productoId == "") {
            mens += "\n- Seleccione un producto";
        }
         if (lote=="") {mens+="\n- Seleccione el numero de Lote";}
        if ((cantidad=="") || (cantidad <= 0 )) {mens+="\n- Inserte una cantidad valida";}
        
        if(presentacion=='M1'){presentacion='Molido'; trans="1"; }
        else if(presentacion=='M1.1'){presentacion='Molido 500 gr.'; trans="0.50";}
        else if(presentacion=='M1.2'){presentacion='Molido 250 gr.'; trans="0.25";}
        if(presentacion=='G1'){presentacion='en Grano'; trans="1"; }
        else if(presentacion=='G1.1'){presentacion='en Grano 500 gr.'; trans="0.50";}
        else if(presentacion=='G1.2'){presentacion='en Grano 250 gr.'; trans="0.25";}
        if(trans==''){trans=1;}
        cantidad=cantidad * trans;
         if (parseInt(cantidad) > parseInt(existencia)) {mens+="\n- La cantidad no puede ser mayor a la existencia de producto";} 

        if (mens != "") {
            alert('Verifique los siguientes campos:\n' + mens);

        } else
        {
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                data: 'operacion=' + operacion + '&cantidad=' + cantidad + "&productoId=" + productoId + "&precio=" + precio + "&lote=" + lote + "&serie=" + serie + "&opcion=" + opcion + "&almacenId=" + almacenId+ "&presentacionV=" + presentacion+ "&presentacion=" + trans,
                success: function (html) {

                    html = html.replace(/^\s+|\s+$/g, "");
                    if (html == 'Si') {
                        alert('Esta partida ya existe.......!');
                    } else {

                        imprime_lista();
                    }
                }
            });
        }
    }

    function buscarOrigen(){
         var almacen= $("#anticipo_almacen_id").val();
         var concepto = $("#anticipo_almacen_id option:selected").text()
         if(almacen >= 1){
         $("#anticipo_origen").val(concepto); 
         buscaProducto();
        }else{
            $("#anticipo_origen").val("");
        }
        
    }
</script>    
<?php View::content(); 
$presentacionB = array("" => "Seleccione");?>
<body id="cuerpo_principal">

    <div id="form_container" style="width:100%;" >
        <br>
        <h1><a></a></h1>
        <div id="titulo_superior"> 
            <div id="texto_superior"  >
                <?php echo "REGISTRO DE ANTICIPO" ?> 
            </div>
            <div style="text-align:right;margin: 0 0; width:49%; float: left; ">
                <div class='btn'>
                    <?php
                    echo Html::linkAction('listadoAnticipo', Html::img('verLista.png', 'cancel', 'style="text-align:center;width:90px;  padding:2px;"'), '');
                    ?>
                </div>
            </div>
        </div>
        <?php echo Form::open("venta/" . $accion); ?>
        <?php echo Form::hidden("anticipo.id"); ?>



        <div id="margen" >
            <div class="form-row">


                <?php echo Form::hidden('anticipo.tipo_documento', 'maxlength="20" required class="form-control"   ', "VENTA"); ?>

                   <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Origen:    
                            </div>
                            <?php
                             echo Form::hidden('anticipo.origen',' class="form-control" ');
                             echo Form::dbSelect("anticipo.almacen_id", "descripcion", array("almacen", "listar"), 'Seleccione..', 'class="form-control" onchange="buscarOrigen()" '); 
                            ?>
                        </div>
                    </div> 
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Documento:    
                            </div>
<?php echo Form::text('anticipo.documento', ' readonly="readonly" maxlength="20" required class="form-control"   ', $num); ?>
                        </div>
                    </div> 
                </div>

                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Fecha:    
                            </div>
<?php echo form::date('anticipo.fecha_anticipo', 'placeholder="dd-mm-aa" required class="form-control"', date('Y-m-d')); ?>
                        </div>
                    </div> 
                </div>
               <div class="col-sm-8">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">    Cliente:    
                            </div>
<?php echo Form::dbSelect("anticipo.cliente_id", "nombrecompleto", array("cliente", "listar"), 'Seleccione..', ' class="form-control" required '); ?>
                        </div>
                    </div> 
                </div>

                
                


            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">Datos Cliente </div>
                <div class="panel-body">
                    <div id="cliente">
                        <table width="100%" border="0">
                            <tr>
                                <td width="104"><label> Nombre:</label></td>
                                <td width="551"><input name="anticipo.nombre" id="anticipo.nombre" type="text" size="100"  class='form-control' readonly="readonly"/></td>
                            </tr>
                            <tr>
                                <td><label> Direccion:</label></td>
                                <td><input type="text" name="anticipo.direccion" id="anticipo.direccion" size="100"  class='form-control' readonly="readonly"/></td>
                            </tr>
                            <tr>
                                <td><label> RFC:</label></td>
                                <td><input name="anticipo.rfc" id="anticipo.rfc" type="text" size="15"   class="letra" readonly="readonly"/></td> 
                            </tr>
                        </table>
                    </div>   
                </div>
            </div>
            
<?php $ar2 = array('Contado', 'Credito'); ?>
            
             <div class="panel panel-primary">
                <div class="panel-heading">Datos Producto </div>
                <div class="panel-body">
                    <div class="form-row">
                        <div class="col-md-2 ">
                            <label for="validationCustomUsername">C. Inventario</label>
                            <div class="input-group">
<div id="productoEs">
<?php echo Form::text("venta.producto_id", ' class="form-control"'); ?>
</div>
                            </div>
                        </div> 
                        <div class="col-md-2 " id="tipoVenta">
                            
                            
                            <label >C. Venta</label>
                            <div class="input-group">
                                <div  id="etiqueta1" >
                                    <?php echo Form::Select('presentacionV', $presentacionB, 'class="form-control"', ''); ?>
                                </div>
                            </div>
                        
                        </div>
                        
                        <div class="col-md-2 ">
                            <label >Lote</label>
                            <div class="input-group">
                                <div  id="loteProducto" >

                                    <?php echo Form::text("lote",  'class="form-control" '); ?>
                                </div>
                            </div>
                        </div> 

                         
                        <div class="col-md-2 ">
                            <label >precio</label>
                            <div class="input-group">
                                <div id="almacen">
<?php echo Form::text("venta.precio",  'class="form-control" '); ?>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-2 ">
                            <label >cantidad</label>
                            <div class="input-group">

<?php echo Form::number('venta.cantidad', ' class="form-control"  min="0" step="0.1"', '0'); ?>

                            </div>
                        </div> 


                         






                        
                        <div class="col-md-1 ">
                            <label >existencia</label>
                            <div class="input-group">
                                <div id="almacen">
<?php echo Form::text("existencia",  'class="form-control" readonly="readonly"'); ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-1 ">
                            <label >.</label>
                            <div class="input-group">
<?php echo Form::button("Agregar", "id='Agregar' style='width:98%;' class='btn-success btn' ") ?>
                            </div>
                        </div> 

                    </div>      
                    <br>

                    <div id="resultado" style="min-height: 300px;max-height: 300px;   border-bottom-color:#fff;overflow: auto;position: relative;  "> <?php print"<script> imprime_lista() </script>"; ?></div>
                    </br>
                    <table width="100%" border="0">
                        <tr>
                            <td style="width: 80%;text-align: right;"> SubTotal $ </td>
                            <td style="width: 1%;"></td>
                            <td><?php echo Form::text('dsubtotal', '  class="form-control"  style="text-align:right;" '); ?> </td>
                        </tr>
                        <tr>
                            <td style="width: 80%;text-align: right;"> Impuesto $ </td>
                            <td style="width: 1%;"></td>
                            <td><?php echo Form::text('dimpuesto', '  class="form-control" style="text-align:right;"  '); ?> </td>
                        </tr>
                        <tr>
                            <td style="width: 80%;text-align: right;"> Total $ </td>
                            <td style="width: 1%;"></td>
                            <td><?php echo Form::text('dtotal', '  class="form-control" style="text-align:right;"  '); ?> </td>
                        </tr>
                    </table>

                    <br>
                   
                    <div class="col-sm-7">
                        <div class="form-group">
                            <!--
                            <div class="input-group">
                                <div class="input-group-addon">       Capturo:    
                                </div>
<?php echo Form::text('venta.capturo', ' required class="form-control"   '); ?>
                            </div>  !-->
                        </div> 
                    </div>

                </div>
            </div>
            <fieldset style="padding: 15px;">
                <legend><b>Datos del Anticipo :</b></legend> 
               

                <div class="col-sm-9">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Forma de pago:
                            </div>
<?php echo Form::dbSelect("anticipo.concepto_id", 'concepto', array('conceptos', 'listar', 0), '- Seleccione -', " class='form-control' required"); ?>
                        </div>
                    </div> 
                </div>

                    <div id="cajaDetalle" style="display: none">
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Referencia:    
                            </div>
<?php echo Form::text('anticipo.referencia', 'maxlength="30" class="form-control"  '); ?>
                        </div>
                    </div> 
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Fecha de documento:    
                            </div>
<?php echo Form::date('anticipo.fecha_referencia', 'type="text" class="form-control" placeholder="dd-mm-aa" '); ?> 
                        </div>
                    </div> 
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Cuenta Bancaria:    
                            </div>
<?php echo Form::dbSelect("anticipo.bancos_cuentas_id", 'cuenta', array('bancosCuentas', 'listarCuentasBancos', 0), '- Seleccione -', " class='form-control '  "); ?>
                        </div>
                    </div> 
                </div>
                    </div>
                    
                <div class="col-sm-12">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Uso del CFDI :    
                            </div>
<?php echo Form::dbSelect("anticipo.uso_id", 'descripcion', array('usoCfdi', 'listar', 0), '- Seleccione -', " class='form-control input-sm' required  "); ?>
                        </div>
                    </div> 
                </div>
                <table width="100%" border='0'>



                    <tr>
                        <td colspan="2" rowspan="3" width="60%">
                            <label class="description"> Observaciones </label>  
<?php echo Form::textarea('anticipo.observacion', '  class="form-control"  '); ?>
                        </td> 
                        <td width="20%" style="text-align: right">Importe  $</td>
                        <td width="20%" valign="middle">
                            <div style="margin-top: 4px" class="input-group">

<?php echo Form::text('anticipo.importe', 'maxlength="20" class="form-control" size="10" style="text-align:right;"', 0); ?>

                            </div>
                        </td>
                    </tr>

                    
                </table>    
        </div>

    </fieldset>


<?php $url = "'" . PUBLIC_PATH . "venta/listadoAnticipo'"; ?>
    <table width="100%">
        <tr align="center">
            <td width="33%">     
<?php echo Form::button("Cancelar", 'class="btn btn-lg btn-danger" onclick="window.location = ' . $url . '" '); ?>
            </td>
            <td>

            </td>
            <td width="33%">
<?php echo Form::submit((($accion == 'crearAnticipo') ? 'Guardar' : 'Actualizar'), 'type="submit" class="btn btn-lg btn-primary"'); ?>       
            </td>
        </tr>
    </table>

</div> 
</div>
</br>
<?php echo Form::close(); ?>

</body>

<script type="text/javascript">
   
    $("#Agregar").click(function () {

        agregarPartida();

    });
    $("#anticipo_cliente_id").change(function () {
        buscaCliente();

    });

   
    $("#anticipo_concepto_id").change(function () {
        var idConcepto = $('#anticipo_concepto_id').val();
        
        if (idConcepto != '') {
            operacion = 'BUSCA_MOVIMIENTO';
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/funciones'; ?>",
                data: "operacion=" + operacion + "&idConcepto=" + idConcepto,
                success: function (html) {
                    var aux = html;
                    aux = aux.replace(/^\s+|\s+$/g, "");
                    $('#tipo_operacion').val(aux);
                    if (aux != "C") {
                        $('#cambio').hide();
                        $('#etiqCb').hide();
                        $('#p').hide();
                        //MUESTRA LOS CAMPOS COMPLEMENTARIOS PARA FORMA DE PAGO EN (BANCO)
                        $('#cajaDetalle').show();
                        operacion = 'BUSCA_BANCO';
                        $.ajax({
                            type: "POST",
                            url: "<?php echo PUBLIC_PATH . 'venta/funciones'; ?>",
                            data: "operacion=" + operacion,
                            success: function (html) {

                                $("#bancoI").html(html);
                            }
                        });


                    } else {
                        $('#cambio').show();
                        $('#etiqCb').show();
                        $('#p').show();
                        //OCULTA LOS CAMPOS COMPLEMENTARIOS PARA FORMA DE PAGO EN (BANCO)
                        $('#cajaDetalle').hide();
                       


                    }
                }
            });
        }

    });
    $("#importe_recibido").keyup(function(){
     validaMonto();
 }); 
 
    Number.prototype.formatMoney = function(decPlaces, thouSeparator, decSeparator) {
   var n = this,
   decPlaces = isNaN(decPlaces = Math.abs(decPlaces)) ? 2 : decPlaces,
   decSeparator = decSeparator === undefined ? "." : decSeparator,
   thouSeparator = thouSeparator === undefined ? "," : thouSeparator,
   sign = n < 0 ? "-" : "",
   i = parseInt(n = Math.abs(+n || 0).toFixed(decPlaces)) + "",
   j = (j = i.length) > 3 ? j % 3 : 0;
   return sign + (j ? i.substr(0, j) + thouSeparator : "") + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + thouSeparator) + (decPlaces ? decSeparator + Math.abs(n - i).toFixed(decPlaces).slice(2) : "");
};
</script>  






