<script>
    function imprime_lista()
    {
        var operacion = 'MOSTRAR_LISTA'
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "operacion=" + operacion,
            success: function (html) {
                $("#resultado").html(html);
                $("#dsubtotal").val($("#iSubtotal").val());
                $("#dimpuesto").val($("#iImpuesto").val());
                $("#dtotal").val($("#iTotal").val());
            }
        });

    }
    function buscaDetalle()
    {
        var productoId = $('#cotizacion_producto_id').val();
        var operacion = 'MOSTRAR_DETALLE'
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'inventario/libreriaInventario/'; ?>",
            data: "productoId=" + productoId + "&operacion=" + operacion,
            success: function (html) {
                html = "lote";
                html = html.replace(/^\s+|\s+$/g, "");
                $('#opcion').val(html);
                if (html == "lote") {
                    $('#loteProducto').show();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').hide();
                    $('#serie').val('');
                    $('#numInventario').val('');

                } else if (html == "serie") {
                    $('#loteProducto').hide();
                    $('#serieProducto').show();
                    $('#inventarioProducto').hide();
                    $('#numInventario').val('');
                    $('#lote').val('');
                } else if (html == "loteInventario") {
                    $('#loteProducto').show();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').show();
                    $('#serie').val('');
                } else if (html == "serieInventario") {
                    $('#loteProducto').hide();
                    $('#serieProducto').show();
                    $('#inventarioProducto').show();
                    $('#lote').val('');
                } else if (html == "soloInventario") {
                    $('#loteProducto').hide();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').show();
                    $('#lote').val('');
                    $('#serie').val('');
                } else {
                    $('#inventarioProducto').hide();
                    $('#loteProducto').hide();
                    $('#serieProducto').hide();
                    $('#serie').val('');
                    $('#lote').val('');
                    $('#numInventario').val('');

                }
                //  $("#detalleProducto").html(html);
            }
        });

    }
    function buscaUnidadPrecio() {
        var productoId = $('#cotizacion_producto_id').val();

        var operacion = "BUSCA_UNIDADPRECIO";
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "productoId=" + productoId + "&operacion=" + operacion,
            success: function (html) {
               
                separador = ","
                cadena=html.split(separador)
               
                var valor=cadena[1];
                 $("#cotizacion_precio").val(valor);
                  
            }
        });
    }
    function buscaCliente() {
        var clienteId = $('#cotizacion_cliente_id').val();
        if (clienteId > 0) {
            var operacion = "BUSCA_CLIENTE_C";
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                data: "clienteId=" + clienteId + "&operacion=" + operacion,
                success: function (html) {
                    $("#cliente").html(html);
                }
            });
        }
    }
    function agregarPartida()
    {
trans=0;
        var operacion = 'AGREGAR_PARTIDA';
        var cantidad = $('#cotizacion_cantidad').val();
        var productoId = $('#cotizacion_producto_id').val();
        var precio = $('#cotizacion_precio').val();
        var comentario = $('#cotizacion_comentario').val();
        var presentacionVe=$('#presentacionVenta').val();
        if(presentacionVe=='T') var presentacion = $('#presentacionT').val();
        else {
            var presentacion = $('#presentacionV').val();
            trans=presentacion;
         
        }
        var serie = "";
        var lote = $('#lote').val();
        var opcion = 'lote';
        var mens = "";
        var re = /,/g;
        cantidad = cantidad.replace(re, "");

        if (cantidad == "") {
            mens += "\n- Inserte una cantidad valida";
        }
        if (productoId == "") {
            mens += "\n- Elija un producto";
        }
        if(presentacion=='M1'){presentacion='Molido'; trans="1"; }
        else if(presentacion=='M1.1'){presentacion='Molido 500 gr.'; trans="0.50";}
        else if(presentacion=='M1.2'){presentacion='Molido 250 gr.'; trans="0.25";}
        if(presentacion=='G1'){presentacion='en Grano'; trans="1"; }
        else if(presentacion=='G1.1'){presentacion='Grano 500 gr.'; trans="0.50";}
        else if(presentacion=='G1.2'){presentacion='Grano 250 gr.'; trans="0.25";}
        if(trans==''){trans=1;}
        cantidad=cantidad * trans;

        if (mens != "") {
            alert('Verifique los siguientes campos:\n' + mens);

        } else
        {
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                data: 'operacion=' + operacion + '&cantidad=' + cantidad + "&productoId=" + productoId + "&precio=" + precio + "&lote=" + lote + "&serie=" + serie + "&opcion=" + opcion+ "&presentacionV=" + presentacion+ "&presentacion=" + trans+ "&comentario=" + comentario,
                success: function (html) {

                    html = html.replace(/^\s+|\s+$/g, "");
                    if (html == 'Si') {
                        alert('Esta partida ya existe.......!');
                    } else {

                        imprime_lista();
                    }
                }
            });
        }
    }

    function quitar_partida(linea)
    {

        var operacion = 'QUITAR_PARTIDA'
        var linea = linea;

        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "operacion=" + operacion + "&linea=" + linea,
            success: function (html) {
                imprime_lista();
            }
        });


    }
    
    function buscaCatalogo() {
        var empresaId = $('#empresaE').val();
        if (empresaId > 0) {
            var operacion = "BUSCA_CATALOGO";
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                data: "empresaId=" + empresaId + "&operacion=" + operacion,
                success: function (html) {
                    $("#catalogoEs").html(html);
                    $('#cotizacion_empresa').val($('#empresaE option:selected').text());
                     $('#cotizacion_empresa_id').val($('#empresaE').val());
                }
            });
        }
    }
    
   
    function asignaPrecio(valor) {
       
        if (valor > 0) {
            var operacion = "BUSCA_COSTO";
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                    data: "valor=" + valor + "&operacion=" + operacion,
                success: function (html) {
                    $('#cotizacion_costo_envio').val(html);
                    $('#cotizacion_codigo_envio').val($('#venta_costo_id option:selected').text());
                    $('#cotizacion_codigo_envio_id').val($('#venta_costo_id').val());
                }
            });
        }
    }
    
    function buscarFolio(valor){
         if (valor > 0) {
            var operacion = "BUSCA_SERIE";
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                    data: "valor=" + valor + "&operacion=" + operacion,
                success: function (html) {
                    $('#cotizacion_folio').val(html);
                }
            });
        }else{
         $('#cotizacion_folio').val("");
        }
        
    }
    
</script>    
<?php View::content(); 
$presentacionB = array("" => "Seleccione");?>
<body id="cuerpo_principal">

    <div id="form_container" style="width:100%;" >
        <br>
        <h1><a></a></h1>
        <div id="titulo_superior"> 
            <div id="texto_superior"  >
                <?php echo "Cotización" ?> 
            </div>
            <div style="text-align:right;margin: 0 0; width:49%; float: left; ">
                <div class='btn'>
                    <?php
                    echo Html::linkAction('listadoCotizacion', Html::img('verLista.png', 'cancel', 'style="text-align:center;width:90px;  padding:2px;"'), '');
                    ?>
                </div>
            </div>
        </div>
        <?php echo Form::open("venta/" . $accion); ?>
        <?php echo Form::hidden("cotizacion.id"); ?>



        <div id="margen" >
            <div class="form-row">


                <?php echo Form::hidden('cotizacion.tipo_documento', 'maxlength="20" required class="form-control"   ', "COTIZACION"); ?>

                <div class="col-sm-2">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Serie:    
                            </div>
                            
                        <?php $ar2 = array("" =>'Seleccione', "2" =>'COV', "8" =>'COT'); ?>
                       <?php echo Form::Select('cotizacion.serie_id', $ar2," class='form-control' required onchange='buscarFolio(this.value)' ");   ?>
                        </div>
                    </div> 
                </div>
                
                <div class="col-sm-2">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Folio:    
                            </div>
                            <?php echo Form::text('cotizacion.folio', ' readonly="readonly" maxlength="20" required class="form-control"   '); ?>
                        </div>
                    </div> 
                </div>

                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Fecha:    
                            </div>
                            <?php echo form::date('cotizacion.fecha_documento', 'placeholder="dd-mm-aa" required class="form-control"', date('Y-m-d')); ?>
                        </div>
                    </div> 
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">    Cliente:    
                            </div>
                            <?php echo Form::dbSelect("cotizacion.cliente_id", "nombrecompleto", array("cliente", "listar"), 'Seleccione..', ' class="form-control" '); ?>
                        </div>
                    </div> 
                </div>


            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">Datos Cliente </div>
                <div class="panel-body">
                    <div id="cliente">
                        <table width="100%" border="0">
                            <tr>
                                <td width="104"><label> Cliente:</label></td>
                                <td width="551"><input name="nombre" id="nombre" type="text" size="40"  class="letra" readonly="readonly"/></td>
                            </tr>
                            <tr>
                                <td><label> Direccion:</label></td>
                                <td><input type="text" name="direccion" id="direccion" size="50"  class="letra" readonly="readonly"/></td>
                            </tr>
                            <tr>
                                <td><label> Telefono:</label></td>
                                <td><input name="rfc" id="rfc" type="text" size="15"   class="letra" readonly="readonly"/></td> 
                            </tr>
                            <tr>
                                <td><label> Email:</label></td>
                                <td><input name="rfc" id="rfc" type="text" size="25"   class="letra" readonly="readonly"/></td> 
                            </tr>
                            <tr>
                                <td><label> Organizacion:</label></td>
                                <td><input name="rfc" id="rfc" type="text" size="55"   class="letra" readonly="readonly"/></td> 
                            </tr>
                        </table>
                    </div>   
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">Datos Producto </div>
                <div class="panel-body">
                    <div class="form-row">
                        <div class="col-md-3 mb-3">
                            <label for="validationCustomUsername">Producto</label>
                            <div class="input-group">

                                <?php echo Form::dbSelect("cotizacion.producto_id", "descripcion", array("producto", "listarEntrada"), 'Seleccione..', ' class="form-control"'); ?>

                            </div>
                        </div> 
                        <div class="col-md-2 " id="tipoVenta">
                            
                            
                            <label >C. Venta</label>
                            <div class="input-group">
                                <div  id="etiqueta1" >
                                    <?php echo Form::Select('presentacionV', $presentacionB, 'class="form-control"', ''); ?>
                                </div>
                            </div>
                        
                        </div>
                        <div class="col-md-2 ">
                            <label >cantidad</label>
                            <div class="input-group">

                                <?php echo Form::number('cotizacion.cantidad', ' class="form-control"  ','0'); ?>

                            </div>
                        </div> 


                       

                        <div class="col-md-2 ">
                            <label >Precio</label>
                            <div class="input-group">
                               
                                  <?php echo Form::text('cotizacion.precio', '  class="form-control"  ','0'); ?>
                                
                            </div>
                        </div> 
                        <div class="col-md-2 ">
                            <label >Observacion</label>
                            <div class="input-group">
                               
                                  <?php echo Form::text('cotizacion.comentario', '  class="form-control"  '); ?>
                                
                            </div>
                        </div> 
                        <div class="col-md-1 ">
                            <label >.</label>
                            <div class="input-group">
                                <?php echo Form::button("Agregar", "id='Agregar' style='width:98%;' class='btn-success btn' ") ?>
                            </div>
                        </div> 

                    </div>      


                    <div id="resultado" style="height: 200px; border-bottom:1px;  border-bottom-color:#000; "> <?php print"<script> imprime_lista() </script>"; ?></div>
                    </br>
                    <table width="100%" border="0">
                        <tr>
                            <td style="width: 80%;text-align: right;"> SubTotal $ </td>
                            <td style="width: 1%;"></td>
                            <td><?php echo Form::text('dsubtotal', '  class="form-control"  style="text-align:right;" '); ?> </td>
                        </tr>
                        <tr>
                            <td style="width: 80%;text-align: right;"> Impuesto $ </td>
                            <td style="width: 1%;"></td>
                            <td><?php echo Form::text('dimpuesto', '  class="form-control" style="text-align:right;"  '); ?> </td>
                        </tr>
                        <tr>
                            <td style="width: 80%;text-align: right;"> Total $ </td>
                            <td style="width: 1%;"></td>
                            <td><?php echo Form::text('dtotal', '  class="form-control" style="text-align:right;"  '); ?> </td>
                        </tr>
                    </table>
                    <br/>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon"> Empresa Envio:    
                                </div>
                                <?php echo Form::dbSelect("empresaE", 'nombre', array('empresa', 'listar', 0), '- Seleccione -', " class='form-control' onchange='buscaCatalogo()' "); ?>
                                <?php echo Form::hidden("cotizacion.empresa", "class='form-control' "); ?>
                                <?php echo Form::hidden("cotizacion.empresa_id", "class='form-control' "); ?>
                            </div>
                        </div> 
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon"> Catalogo Costo:    
                                </div>
                                <div id="catalogoEs">
                                <?php echo Form::dbSelect("venta.costo_id", 'costo', array('costoEnvio', 'datos', 0), '- Codigo, kilos, Costo -', " class='form-control' onchange='asignaPrecio(this.value)'"); ?>
                                    
                                </div>
                                <?php echo Form::hidden("cotizacion.codigo_envio", "class='form-control' "); ?>
                                <?php echo Form::hidden("cotizacion.codigo_envio_id", "class='form-control' "); ?>
                                </div>
                        </div> 
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon">Costo Envio:    
                                </div>
                                <?php echo Form::text("cotizacion.costo_envio", "class='form-control' "); ?>
                            </div>
                        </div> 
                    </div>
                    <table style="width: 100%" border="0">

                        <tr >
                            <td style="width: 5%">Observaciones:</td>
                            <td><?php echo Form::textarea('cotizacion.observacion', '  class="form-control"  '); ?></td>

                        </tr>
                    </table>
                    <br>
            
                    <div class="col-sm-8">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon">       Capturo:    
                                </div>
                                <?php echo Form::text('cotizacion.capturo', ' required class="form-control"   '); ?>
                            </div>
                        </div> 
                    </div>
                   
                </div>
                
                <div class="panel panel-success">
                <div class="panel-heading"> </div>
                <div class="panel-body">
                    <div class="form-row">
                        <div class="col-sm-6">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Cuenta de deposito:    
                            </div>
<?php echo Form::dbSelect("cotizacion.bancos_cuentas_id", 'cuenta', array('bancosCuentas', 'listarCuentasBancos', 0), '- Seleccione -', " class='form-control required'  "); ?>
                        </div>
                    </div> 
                </div>
                        <div class="col-sm-6">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">Ciclo Cosecha:    
                            </div>
<?php echo Form::dbSelect("cotizacion.ciclo", 'ciclo', array('lote', 'ciclos', 0), '- Seleccione -', " class='form-control required '  "); ?>
                        </div>
                    </div> 
                </div>
                    </div>
                </div>
                </div>
            </div>  
            <?php $url = "'" . PUBLIC_PATH . "venta/listadoCotizacion'"; ?>
            <table width="100%">
                <tr align="center">
                    <td width="33%">     
                        <?php echo Form::button("Cancelar", 'class="btn btn-lg btn-danger" onclick="window.location = ' . $url . '" '); ?>
                    </td>
                    <td>

                    </td>
                    <td width="33%">
                        <?php echo Form::submit((($accion == 'crearCotizacion') ? 'Guardar' : 'Actualizar'), 'type="submit" class="btn btn-lg btn-primary"'); ?>       
                    </td>
                </tr>
            </table>

        </div> 
    </div>
    </br>
    <?php echo Form::close(); ?>

</body>

<script type="text/javascript">
    $("#cotizacion_producto_id").change(function () {
        buscaUnidadPrecio()
        buscaPresentacion();
    });
    $("#cotizacion_cliente_id").change(function () {
        buscaCliente();

    });

    $("#Agregar").click(function () {

        agregarPartida();

    });
    function buscaPresentacion() {
        var productoId = $('#cotizacion_producto_id').val();
            var operacion = "TIPO_PRESENTACION";
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                data: "productoId=" + productoId + "&operacion=" + operacion,
                success: function (html) {
                    $("#tipoVenta").html(html);
                }
            });
        
    }
</script>  






