<script>
    function imprime_lista()
    {
        var operacion = 'MOSTRAR_LISTA_VENTA'
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "operacion=" + operacion,
            success: function (html) {
                $("#resultado").html(html);
                 actualizaEnvio();
            }
        });

    }
    function buscaAlmacen() {
	var productoId 	=	$('#venta_producto_id').val();
        
        var operacion="BUSCA_ALMACEN";
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
          data: "productoId=" + productoId + "&operacion="+operacion,
          success: function(html){
            $("#almacen").html(html);
          }
        });
        } 
        function buscaProveedor() {
	var proveedorId 	=	$('#venta_proveedor_id').val();
        if(proveedorId >0 ){
        var operacion="BUSCA_PROVEEDOR";
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'inventario/libreriaInventario/'; ?>",
          data: "proveedorId=" + proveedorId + "&operacion="+operacion,
          success: function(html){
            $("#proveedor").html(html);
          }
        });
        }
        }
    function buscaDetalle()
    {
        var productoId = $('#venta_producto_id').val();
        var operacion = 'MOSTRAR_DETALLE'
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'inventario/libreriaInventario/'; ?>",
            data: "productoId=" + productoId + "&operacion=" + operacion,
            success: function (html) {
                html = "lote";
                html = html.replace(/^\s+|\s+$/g, "");
                $('#opcion').val(html);
                if (html == "lote") {
                    $('#loteProducto').show();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').hide();
                    $('#serie').val('');
                    $('#numInventario').val('');

                } else if (html == "serie") {
                    $('#loteProducto').hide();
                    $('#serieProducto').show();
                    $('#inventarioProducto').hide();
                    $('#numInventario').val('');
                    $('#lote').val('');
                } else if (html == "loteInventario") {
                    $('#loteProducto').show();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').show();
                    $('#serie').val('');
                } else if (html == "serieInventario") {
                    $('#loteProducto').hide();
                    $('#serieProducto').show();
                    $('#inventarioProducto').show();
                    $('#lote').val('');
                } else if (html == "soloInventario") {
                    $('#loteProducto').hide();
                    $('#serieProducto').hide();
                    $('#inventarioProducto').show();
                    $('#lote').val('');
                    $('#serie').val('');
                } else {
                    $('#inventarioProducto').hide();
                    $('#loteProducto').hide();
                    $('#serieProducto').hide();
                    $('#serie').val('');
                    $('#lote').val('');
                    $('#numInventario').val('');

                }
                //  $("#detalleProducto").html(html);
            }
        });

    }
    function buscaUnidadPrecio() {
        var productoId = $('#venta_producto_id').val();

        var operacion = "BUSCA_UNIDADPRECIO";
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "productoId=" + productoId + "&operacion=" + operacion,
            success: function (html) {

                separador = ","
                cadena = html.split(separador)
                $("#etiqueta").html(cadena[0]);
                var valor = cadena[1];
                $("#venta_precio").val(valor);

            }
        });
    }
    function buscaCliente() {
        var clienteId = $('#venta_cliente_id').val();
        if (clienteId > 0) {
            var operacion = "BUSCA_CLIENTE";
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                data: "clienteId=" + clienteId + "&operacion=" + operacion,
                success: function (html) {
                    $("#cliente").html(html);
                }
            });
        }
    }
    function agregarPartida()
    {

        var operacion = 'AGREGAR_PARTIDA_VENTA';
        var cantidad = $('#venta_cantidad').val();
        var productoId = $('#venta_producto_id').val();
        var precio = $('#venta_precio').val();
        var almacenId 	=	$('#venta_almacen_id').val();
var serie="";
var lote 	=	$('#lote').val();
var opcion='lote';
        var mens = "";
        var re = /,/g;
        cantidad = cantidad.replace(re, "");

        if (cantidad == "") {
            mens += "\n- Inserte una cantidad valida";
        }
        if (productoId == "") {
            mens += "\n- Elija un producto";
        }



        if (mens != "") {
            alert('Verifique los siguientes campos:\n' + mens);

        } else
        {
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
                data: 'operacion=' + operacion + '&cantidad=' + cantidad + "&productoId=" + productoId + "&precio=" + precio + "&lote=" + lote + "&serie=" + serie + "&opcion=" + opcion+ "&almacenId=" + almacenId,
                success: function (html) {

                    html = html.replace(/^\s+|\s+$/g, "");
                    if (html == 'Si') {
                        alert('Esta partida ya existe.......!');
                    } else {

                        imprime_lista();
                      
                    }
                }
            });
        }
    }

    function quitar_partida(linea)
    {

        var operacion = 'QUITAR_PARTIDA_VENTA'
        var linea = linea;

        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH . 'venta/libreriaVenta/'; ?>",
            data: "operacion=" + operacion + "&linea=" + linea,
            success: function (html) {
                imprime_lista();
                 
            }
        });


    }
    function actualizaEnvio()
    {
var cantidadT = $('#cantidadT').val();
alert(cantidadT);
if((parseInt(cantidadT) > 0 ) && (parseInt(cantidadT)<=1)){ $('#venta_costo_envio').val("154");}
else if((cantidadT>1) && (cantidadT<=2)) $('#venta_costo_envio').val("182");
else if((cantidadT>2) && (cantidadT<=5)) $('#venta_costo_envio').val("218");
else if((cantidadT>5) && (cantidadT<=7)) $('#venta_costo_envio').val("228");
else if((cantidadT>7) && (cantidadT<=8)) $('#venta_costo_envio').val("244");
else if((cantidadT>8) && (cantidadT<=10)) $('#venta_costo_envio').val("256");
else if((cantidadT>10) && (cantidadT<=12)) $('#venta_costo_envio').val("314");
else if((cantidadT>12) && (cantidadT<=15)) $('#venta_costo_envio').val("334");
else if((cantidadT>15) && (cantidadT<=20)) $('#venta_costo_envio').val("366");
else if((cantidadT>20) && (cantidadT<=25)) $('#venta_costo_envio').val("404");
else if((cantidadT>25) && (cantidadT<=30)) $('#venta_costo_envio').val("446");
else if((cantidadT>30) && (cantidadT<=40)) $('#venta_costo_envio').val("516");
else if((cantidadT>40) && (cantidadT<=50)) $('#venta_costo_envio').val("606");
else if((cantidadT>50) && (cantidadT<=60)) $('#venta_costo_envio').val("828");
else if((cantidadT>60) && (cantidadT<=70)) $('#venta_costo_envio').val("934");
else if((cantidadT>70) && (cantidadT<=75)) $('#venta_costo_envio').val("954");
else if((cantidadT>75) && (cantidadT<=80)) $('#venta_costo_envio').val("1008");
else if((cantidadT>75) && (cantidadT<=90)) $('#venta_costo_envio').val("1188");
else if((cantidadT>75) && (cantidadT<=100)) $('#venta_costo_envio').val("1220");
else if((cantidadT>75) && (cantidadT<=130)) $('#venta_costo_envio').val("1590");
else if((cantidadT>75) && (cantidadT<=140)) $('#venta_costo_envio').val("1850");
else if((cantidadT>140)  ) $('#venta_costo_envio').val("2132");
else $('#venta_costo_envio').val("0");


    }
</script>    
<?php View::content(); ?>
<body id="cuerpo_principal">

    <div id="form_container" style="width:100%;" >
        <br>
        <h1><a></a></h1>
        <div id="titulo_superior"> 
            <div id="texto_superior"  >
                <?php echo "VENTA DIRECTA" ?> 
            </div>
            <div style="text-align:right;margin: 0 0; width:49%; float: left; ">
                <div class='btn'>
                    <?php
                    echo Html::linkAction('listadoVenta', Html::img('verLista.png', 'cancel', 'style="text-align:center;width:90px;  padding:2px;"'), '');
                    ?>
                </div>
            </div>
        </div>
        <?php echo Form::open("venta/" . $accion); ?>
        <?php echo Form::hidden("venta.id"); ?>



        <div id="margen" >
            <div class="form-row">


                <?php echo Form::hidden('venta.tipo_documento', 'maxlength="20" required class="form-control"   ', "VENTA"); ?>

                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Origen:    
                            </div>
                            <?php $ar2 = array('OFICINA SAN CRISTOBAL'=>'OFICINA SAN CRISTOBAL', 'BODEGA TUXTLA'=>'BODEGA TUXTLA');
                            echo Form::Select('venta.origen', $ar2, 'OFICINA SAN CRISTOBAL');
                            ?>
                        </div>
                    </div> 
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Documento:    
                            </div>
<?php echo Form::text('venta.documento', ' readonly="readonly" maxlength="20" required class="form-control"   ', $num); ?>
                        </div>
                    </div> 
                </div>

                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">       Fecha:    
                            </div>
<?php echo form::text('venta.fecha_documento', 'placeholder="dd-mm-aa" required class="form-control"', date('d-m-Y')); ?>
                        </div>
                    </div> 
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">    Cliente:    
                            </div>
<?php echo Form::dbSelect("venta.cliente_id", "nombrecompleto", array("cliente", "listar"), 'Seleccione..', ' class="form-control" '); ?>
                        </div>
                    </div> 
                </div>


            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">Datos Cliente </div>
                <div class="panel-body">
                    <div id="cliente">
                        <table width="100%" border="0">
                            <tr>
                                <td width="104"><label> Nombre:</label></td>
                                <td width="551"><input name="nombre" id="nombre" type="text" size="40"  class="letra" readonly="readonly"/></td>
                            </tr>
                            <tr>
                                <td><label> Direccion:</label></td>
                                <td><input type="text" name="direccion" id="direccion" size="50"  class="letra" readonly="readonly"/></td>
                            </tr>
                            <tr>
                                <td><label> RFC:</label></td>
                                <td><input name="rfc" id="rfc" type="text" size="15"   class="letra" readonly="readonly"/></td> 
                            </tr>
                        </table>
                    </div>   
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">Datos Producto </div>
                <div class="panel-body">
                    <div class="form-row">
                        <div class="col-md-3 ">
                            <label for="validationCustomUsername">Producto</label>
                            <div class="input-group">

<?php echo Form::dbSelect("venta.producto_id", "descripcion", array("producto", "listarEntrada"), 'Seleccione..', ' class="form-control"'); ?>

                            </div>
                        </div> 
                        <div class="col-md-2 ">
                            <label >cantidad</label>
                            <div class="input-group">

<?php echo Form::number('venta.cantidad', ' class="form-control"  ', '0'); ?>

                            </div>
                        </div> 


                        <div class="col-md-1 ">
                            <label >.</label>
                            <div class="input-group">
                                <div  id="etiqueta" >

                                </div>
                            </div>
                        </div> 

                       

<?php echo Form::hidden('venta.precio', ' readonly="readonly" class="form-control"  ', '0'); ?>

                            
                        <div class="col-md-2 ">
                            <label for="validationCustomUsername">Lote</label>
                            <div class="input-group">
                                <div  id="loteProducto" >
<?php echo Form::dbSelect("lote", "codigo", array("lote", "listar"), 'Seleccione..', 'class="form-control" '); ?>
                                </div>
                            </div>
                        </div> 

                        <div class="col-md-2 ">
                            <label >Almacen</label>
                            <div class="input-group">
                                <div id="almacen">
<?php echo Form::dbSelect("venta.almacen_id", "descripcion", array("almacen", "listar"), 'Seleccione..', 'class="form-control" '); ?>
                                </div>
                            </div>
                        </div> 
                        <div class="col-md-1 ">
                            <label >.</label>
                            <div class="input-group">
<?php echo Form::button("Agregar", "id='Agregar' style='width:98%;' class='btn-success btn' ") ?>
                            </div>
                        </div> 

                    </div>      
                    <br>

                    <div id="resultado" style="height: 200px; border-bottom:1px;  border-bottom-color:#000; "> <?php print"<script> imprime_lista() </script>"; ?></div>
                    </br>

                    
                    <br>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon">       Costo Envio:    
                                </div>
<?php echo Form::number('venta.costo_envio', ' required class="form-control"   '); ?>
                            </div>
                        </div> 
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <div class="input-group">
                      <!--          <div class="input-group-addon">       Capturo:    
                                </div>
<?php echo Form::text('venta.capturo', ' required class="form-control"   '); ?> !-->
                            </div>
                        </div> 
                    </div>

                </div>
            </div>  
               <fieldset style="padding: 15px;">
                    <legend><b>Datos del Pago :</b></legend> 
    <table width="100%" border='0'>
    <tr>
        <td aling="center" id="etiqCta" style="display:none;" width="15%">
            Forma de pago
        </td >
        <td aling="center" id="etiqR" style="display:none;" width="25%">
            Referencia
        </td >
        <td id="etiqF" style="display:none;" width="25%">
            Fecha de documento
        </td>
        <td aling="center" id="etiqB" style="display:none;" width="25%">
            Cuenta Bancaria
        </td>
    </tr>
    <tr>
        <td id="cta"  width="15%">
           <?php echo Form::dbSelect("concepto_id", 'concepto', array('conceptos', 'listar', 0), '- Seleccione -'," class='element text' ");?>
        </td>
        <td id="refCta" style=" display: none;"  width="25%">
          <?php echo Form::text('referencia', 'maxlength="30" class="element text"  size="12"'); ?>
        </td>
        <td id="fechaD" style=" display:none;"  width="25%">
        <?php echo Form::text('fecha_referencia','type="text" class="form-control1-calend" placeholder="dd-mm-aa" ');?>  
        </td>
        <td id="bancoI" style=" display: none;"  width="25%">
           <?php echo Form::dbSelect("cuenta_id", 'cuenta', array('bancosCuentas', 'listarCuentasBancos', 0), '- Seleccione -'," class='form-control '  ");?>
        </td>
    </tr>
    <tr>
        <td id="usoCFDI"  width="15%">
           Uso del CFDI        </td>
        <td colspan="3" id="usoCFDIetiqueta" >
             
      <?php echo Form::dbSelect("uso_id", 'descripcion', array('usoCfdi', 'listar', 0), '- Seleccione -'," class='form-control input-sm'  ");?>        </td>
    </tr>
    <tr>
        <td colspan="2" rowspan="3" width="50%">
          <label class="description"> Observaciones </label>  <br/>
         <?php echo Form::textarea('venta.observacion', '  class="form-control"  '); ?>
        </td> 
        <td width="25%">Importe recibido $</td>
        <td width="25%">
            <div style="margin-top: -1px; " class="input-group">
                <span class="input-group-addon">
                <?php echo Form::text('importe_recibido','maxlength="20" class="form-control" size="10" style="text-align:right;"',0);?>
                </span>
            </div>
        </td>
    </tr>
    <tr>
        <td width="25%"></td>
        <td width="25%">
            
        </td>
    </tr>
    <tr>
        <td width="25%">Cambio           $</td>
        <td width="25%">
            <div style="margin-top: -1px; " class="input-group">
                <span class="input-group-addon">
                <?php echo  Form::text('cambio','readonly="readonly" maxlength="20" class="form-control" size="10" style="text-align:right;"',0);?>                   
                    </span>
            </div>
        </td>
    </tr>
    </table>
    </fieldset>
            
            
<?php $url = "'" . PUBLIC_PATH . "venta/listadoVenta'"; ?>
            <table width="100%">
                <tr align="center">
                    <td width="33%">     
<?php echo Form::button("Cancelar", 'class="btn btn-lg btn-danger" onclick="window.location = ' . $url . '" '); ?>
                    </td>
                    <td>

                    </td>
                    <td width="33%">
<?php echo Form::submit((($accion == 'crearVenta') ? 'Guardar' : 'Actualizar'), 'type="submit" class="btn btn-lg btn-primary"'); ?>       
                    </td>
                </tr>
            </table>

        </div> 
    </div>
    </br>
<?php echo Form::close(); ?>

</body>

<script type="text/javascript">
    $("#venta_producto_id").change(function () {
        buscaUnidadPrecio();
        buscaAlmacen();
        buscaDetalle();
    });
    $("#venta_cliente_id").change(function () {
        buscaCliente();

    });

    $("#Agregar").click(function () {

        agregarPartida();

    });
    $("#concepto_id").change(function(){
    var idConcepto 	=	$('#concepto_id').val();
    if(idConcepto != ''){
    operacion='BUSCA_MOVIMIENTO';
    $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'venta/funciones'; ?>",
          data: "operacion=" + operacion + "&idConcepto=" + idConcepto,
          success: function(html){
var aux=html;
aux=aux.replace(/^\s+|\s+$/g, "");
$('#tipo_operacion').val(aux);
        if( aux != "C"){
      $('#cambio').hide();
        $('#etiqCb').hide();
        $('#p').hide();
        //MUESTRA LOS CAMPOS COMPLEMENTARIOS PARA FORMA DE PAGO EN (BANCO)
        $('#refCta').show();
        $('#etiqR').show();
        $('#fechaD').show();
        $('#etiqF').show();
        $('#bancoI').show();
        $('#etiqB').show();
        $('#etiqCta').show();
        
         operacion='BUSCA_BANCO';
    $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'venta/funciones'; ?>",
          data: "operacion=" + operacion,
          success: function(html){
          
        $("#bancoI").html(html);
          }
        });
        
        
        }else{
             $('#cambio').show();
         $('#etiqCb').show();
         $('#p').show();
         //OCULTA LOS CAMPOS COMPLEMENTARIOS PARA FORMA DE PAGO EN (BANCO)
         $('#refCta').hide();
         $('#etiqR').hide();
         $('#fechaD').hide();
         $('#etiqF').hide();
         $('#bancoI').hide();
         $('#etiqB').hide();
        
        
        }
          }
        });
        }   
   
});
</script>  






