<?php View::content(); ?>



<body id="principal">
<br/>  
<div id="form_container" >

    

    <?php echo Form::open("venta/envio/".$venta); ?>   
    <?php echo Form::hidden("envio.id"); ?>
    <?php echo Form::hidden( 'envio.venta_id', 'class="form-control"',@$venta); ?>
    <div id="form">
      <div class="col-sm-12">                  
    <div class="panel panel-primary">
        <div class="panel-heading">Datos de Envio</div>
        <div class="panel-body">

            <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Empresa:
                        </div>
                        <?php if (@$envio->empresa_id==null)@$envio->empresa_id=0;?>
<?php echo Form::dbSelect("envio.empresa_id", 'nombre', array('empresa', 'datosEmpresa', @$envio->empresa_id), '- Seleccione -'," class='form-control '  ");?>

                    </div>
                </div>
            </div> 
            <div class="col-sm-8">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Numero de Rastreo:
                        </div>
<?php echo Form::text( 'envio.numero_rastreo', 'class="form-control"'); ?>

                    </div>
                </div>
            </div> 
 <?php if($envio->numero_rastreo!=""){ ?>
            <div class="col-sm-4">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"> 
                           
                            <a href="<?php echo $empresa->link.$envio->numero_rastreo ?> " target="_blank">C O N S U L T A R </a>
                           
                        </div>


                    </div>
                </div>
            </div> <?php } ?>
            <div class="col-sm-6">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Fecha Envio:
                        </div>
<?php echo Form::date( 'envio.fecha_envio', 'class="form-control"'); ?>

                    </div>
                </div>
            </div> 
            <div class="col-sm-6">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Fecha Entrega:
                        </div>
<?php echo Form::date( 'envio.fecha_entrega', 'class="form-control"'); ?>

                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">  Observaciones:
                        </div>
<?php echo Form::textarea( 'envio.observaciones', 'class="form-control"'); ?>

                    </div>
                </div>
            </div>
        
        <table width="100%">
        <tr align="center">
            <td width="100%">     
            
            <?php echo Form::submit(((@$accion == 'crearLote') ? 'Guardar' : 'Actualizar'), 'type="submit" class="btn btn-success btn-lg"'); ?>       
            </td>
        </tr>
        </table>
        </div>
    </div>
</div>       
            
        
     <?php echo Form::close(); ?>
  </div> 
</div>

</body>
<script>
    $("#Salir").click(function(){
        
 });
 
</script>