<?php Tag::css('demo_page'); ?>
<?php Tag::css('demo_table'); ?>
<?php Html::includeCss() ?>
<?php echo Tag::js('jquery.dataTables.min'); ?>
<?php View::content(); ?>    
    <div id="dt_example" style="margin:0 auto; padding:10px 20px; background-color:#ffffff; ">      
        <br />
        <div id="texto_superior"  >
                 <?php echo $encabezado ?> 
            </div>
          
             <div style="text-align:right;margin: 0 0; width:100%; float: left; ">
                <div class='btn'>
                    <?php
                   
                                           
                          echo Html::linkAction('crearCobro',Html::img('nuevo.png','cancel','style="text-align:center;width:75px;  padding:2px;"'),'');
                    
                    
                    ?>
                </div>
            </div> 
        <br />
        <br />
        <table  border="0" width="100%" id="display2" class="display2">
            <thead>
                <tr  style="font-size: 9px;letter-spacing: -0.8px;">
                    <th> #</th>
                    <th width="15%">Cliente</th>
                    <th width="10%"> Monto</th>
                    <th width="10%"> T. Cobro</th>
                    <th>Banco</th>
                   <th>Referencia</th>
                    <th>Fecha Referencia</th>
                     <th>F. Cobro</th>
                     <th></th>
                      <th>Estatus</th>
                      
                    <th>Accion </th>
                    
                    </tr>
            </thead>
            <tbody>
<?php

           $i=1;
            foreach($result as $res){
                        
                        echo "<tr>";
                        echo "<td> ".$i." </td>";
                        echo "<td> ".$res->nombrecompleto." </td>";
                         echo "<td>".$res->monto."</td>";
                        echo "<td>".$res->concepto."</td>";
                            echo "<td>".$res->numero_cuenta."-".$res->nombre_banco ." </td>";
                            echo "<td>".$res->referencia."</td>";
                             echo "<td align='center'>".(($res->fecha_referencia!="")? strftime('%d-%m-%Y',strtotime($res->fecha_referencia)):"")."</td>"; 
                            echo "<td>".(($res->fecha_documento!="")? strftime('%d-%m-%Y',strtotime($res->fecha_documento)):"")."</td>";
                            echo "<td>".$res->tipo."</td>";
                            echo "<td>";
                            if($res->estatus=="1") echo "Activo";
                            else echo "Cancelado";
                            
                            echo "</td>";
                            
                           echo "<td>";
                           
                           echo "</td>";
                           
                            echo "</tr>";   
                            
                        $i++; 
               }
            ?>
            </tbody>
        </table>
        
       
    </div>

<script type="text/javascript" charset="utf-8">

$(function(){
    $("#display2").dataTable ({
            "bAutoWidth": true,
            "iDisplayLength": 10,
            "aLengthMenu": [[10,25,50,100,250,500,-1], [10,25,50,100,250,500,"Todo"]],
            "sPaginationType": "full_numbers",
            "oLanguage": {
                    "aProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "NO EXISTE INFORMACIÓN",
                    "sInfo": "Mostrando desde _START_ hasta _END_ registros",
                    "sInfoEmpty": "Mostrando desde 0 hasta 0 de 0 registros",
                    "sInfoFiltered": "(filtrando de _MAX_ registros en total)",
                    "sSearch": "Buscar",
                    "oPaginate": {
                            "sFirst": "Primero",
                            "sPrevious": "Anterior",
                            "sNext": "Siguiente",
                            "sLast": "Ultimo"
                    }
            }
    });
    
    
});


</script>


<script>
   function actualizar(){
       window.location.reload();
   }
</script> 
