<?php

Load::lib('tcpdf');
Load::lib('funciones');
class reporte extends TCPDF {

  

    public function Header() {
        
    }

    

}



 $pdf = new reporte('P','mm',array(80,'125'));  
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('');
$pdf->SetTitle('Remision-Venta');
$pdf->SetSubject('');

$logo='./img/logoReporte.png';

$pdf->SetFooterData('','',"");
//set margins
$pdf->SetMargins(1,1,1);//PDF_MARGIN_LEFT, '20', PDF_MARGIN_RIGHT
$pdf->SetHeaderMargin('10');//PDF_MARGIN_HEADER
//$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
//$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

$pdf->AddPage();

$matrixPointSize = 10;
$errorCorrectionLevel = 'L';
$importeSubtotal=0;
$logo='./img/logo.png';


$pdf->SetFont('Helvetica','',16);
$html="";
    $html .= '
<div id="divContenido">        
<table  width="100%" > 
  <tr>
    <td  align="center"  style="width:40%;  " ><img src="'. PUBLIC_PATH.'img/logo.png"  alt="logo"  /> </td>	
    <td  align="center"  style="width:60%; font-size:10px;"><br>www.union.majomut.org</td>             
  </tr>   
</table><br><br>';
  
    
$html .= '<table  width="100%" style="font-size:10px;"> 
  <tr>
    <td  >R.F.C.: <b>UPO111114BJ7 </b> </td>
    </tr>
    <tr>
    <td>1a. Cerrada de la Era No. 1</td>
    </tr>
    <tr>
    <td  >Barrio Quinta San Martín C.P.: 29247</td>
    </tr>
    <tr>
    <td  >967 678 31 96 y 967 678 81 06</td>
    </tr>
    <tr>
    <td >ventas@majomut.org <b>\</b> info@majomut.org</td>
    
  </tr>   
</table>';

$html .= '<table  width="100%" style="font-size:10px;"> 
    <tr>
    <td> ------------------------------------ </td>
    </tr>
  <tr>
    <td  >Venta No.: <b>'.$datosCompra->documento.' </b></td>
    </tr>
    <tr>
    <td  >Fecha: <b>'.$datosCompra->fecha_documento.'</b></td>
    </tr>
     <tr>
    <td> ------------------------------------ </td>
    </tr>
</table>';

 
// COLUMNAS


foreach ($detalleCompra as $datos){
    $c1=$datos->cantidad * $datos->precio;
    $html .= '<table  width="100%" style="font-size:9px;"> 
   
  <tr>
  <td width="25%">Cantidad: </td>
    <td  width="80%">'.$datos->cantidad.' '.$datos->unidad.' </td>
    </tr>
    <tr>
    <td>Producto: </td>
    <td  >'.$datos->descripcion.' ('.$datos->lote.')</td>
    </tr>
    <tr>
    <td>Precio: </td>
    <td  >'.$datos->precio.'</td>
    </tr>
    <tr>
    <td>Subtotal: </td>
    <td  >$ '. number_format($c1,2).'</td>
    </tr>
    
    <tr>
    <td  colspan="2"> ------------------------------------ </td>
    </tr>
</table>';
 
} 
$descuento=0;
$importeTotal=0;
$importeTotal=@$datosCompra->subtotal+@$datosCompra->iva-@$descuento+@$datosCompra->costo_envio;
$decimales = $importeTotal - (int) $importeTotal;
$decimales = round($decimales, 2);
$decimales = $decimales * 100;
$decimales = ($decimales == 0) ? "00": $decimales;
$num_letras = new EnLetras();

$txtmetpago = array("01"=>"EFECTIVO", "02"=>"CHEQUE NOMINATIVO", "03"=>"TRANSFERENCIA ELECTRÓNICA DE FONDOS", "04"=>"TARJETA DE CRÉDITO",
                    "05"=>"MONEDERO ELECTRÓNICO", "06"=>"DINERO ELECTRÓNICO", "08"=>"VALES DE DESPENSA", "28"=>"TARJETA DE DÉBITO",
                    "29"=>"TARJETA DE SERVICIO", "99"=>"OTROS");

    $html .= '<table  width="100%" style="font-size:9px;"> 
        <tr>
                
                
                <td width="70%" >SUBTOTAL: </td> 
                <td width="30%"  align="right"><b>$ '.number_format($datosCompra->subtotal, 2, '.', ',').'</b></td> 
              </tr>
              
              <tr>
                <td >IVA: + </td> 
                <td   align="right"> <b>$ '.number_format($datosCompra->iva, 2, '.', ',').'</b></td> 
              </tr>
              <tr>
                <td >ANTICPOS -: </td>    
                <td align="right"><b> $ '.number_format(@$anticipo, 2, '.', ',').'</b></td>
              </tr>
              <tr>
                <td >COSTO DE ENVIO +: </td>    
                <td align="right"><b> $ '.(($datosCompra->costo_envio>1)? number_format($datosCompra->costo_envio, 2, '.', ','):'0.00').'</b></td>
              </tr>
              <tr>
                <td >TOTAL: </td> 
                <td align="right"><b> $ '.number_format($importeTotal, 2, '.', ',').'</b></td> 
              </tr>
              
              ';
$html .= '</table></div>'
        ;  
 ob_end_clean();    
// Print text using writeHTMLCell()
$pdf->writeHTML($html, true, false, true, false, '');
ob_end_clean();
// ---------------------------------------------------------
// Close and output PDF document
// This method has several options, check the source code documentation for more information.
$pdf->Output('remision.pdf', 'I');
 

//============================================================+
// END OF FILE
//============================================================+
 //echo $html;
?>
<script type="text/javascript">
   
    function imprimir() {
  var mywindow = window.open('', 'PRINT', 'height=400,width=600');

    mywindow.document.write('<html><head><title>' + document.title  + '</title>');
    mywindow.document.write('</head><body >');
   
    mywindow.document.write(document.getElementById('divContenido').innerHTML);
    mywindow.document.write('</body></html>');

    mywindow.document.close(); // necessary for IE >= 10
    mywindow.focus(); // necessary for IE >= 10*/

    mywindow.print();
    mywindow.close();
}
    </script>
<button class="oculto-impresion" onclick="imprimir()">Imprimir</button>
